### ISSUE TITLE
Choppy video playback

### ISSUE THREAD

**Issue by tech189** [OrangeJedi/Aerial#10]
**Describe the bug**
When the video plays, it seems to skip quite a few frames, usually I have no issue playing video on this computer!

**To Reproduce**
1. Let the screensaver play

**Expected behavior**
Smooth playback would be nice :)

**Aerial Version**
0.5.0

**Additional context**
Windows 10 v1909 build 18363.752
I have tried with and without the text overlay

**Comment by OrangeJedi** [comment]
Do you get choppy playback when you hit the 'preview' button, or when the screen saver starts?
Have you used a previous version of Aerial that didn't have this problem?
Are the videos play smoothly in the 'videos' tab on the config screen?
Are you using the cache?
Do you have more than one screen that you are playing the video on?

Sorry for all the questions, I'm trying to figure out where your error may be. I hope I can find a solution.

**Comment by tech189** [comment]
I get it both when using the preview and when it starts by itself.
No I just installed it, haven't used a previous version.
Yes the videos play perfectly in the videos tab!
No I am not using the cache because my main drive where Appdata is stored is quite small.
Yes, I am using a single monitor via HDMI coming from my laptop. The laptop is closed though, so just one screen that the video is playing on (I'm not duplicating or extending). I tried it with and without the monitor attached, still skips frames and stutters, the fans seem to spin up as well.

No worries, hopefully we can solve it.

**Comment by OrangeJedi** [comment]
That's good that it plays fine in the video tab; it probably not anything network related then.
You might try downloading just one video (in the video tab) and seeing if playing the downloaded video still causes the choppy playback.
Also, are you using the .scr file or the .zip folder? I've noticed the .scr runs a bit slower.

Can you open your task manager while the screensaver is running to see if it is a resources problem? If you open the app from the command line with `aerial.exe /s /nq` (see [here](https://github.com/OrangeJedi/Aerial/blob/master/CONTRIBUTING.md#how-to-set-up-aerials-dev-environment) for more details) aerial won't quit on mouse movement or key presses.

**Comment by tech189** [comment]
Still getting choppy playback when the videos are cached, unfortunately. I downloaded the zip folder and right clicked the .scr and pressed Install.

Here are some screenshots:
Not cached:
![aerial scr_6Ht7NMuL9w](https://user-images.githubusercontent.com/10728085/78773830-b4442000-798b-11ea-95b1-d0d457b79117.jpg)
Cached:
![aerial scr_0TyYetVX0h](https://user-images.githubusercontent.com/10728085/78773860-c1610f00-798b-11ea-8858-daf701100c0e.jpg)
In full screen playback, it seems to use almost 100% of the GPU:
![Taskmgr_EZAg1tQ2lg](https://user-images.githubusercontent.com/10728085/78774237-53691780-798c-11ea-88fd-663d264ca1e6.png)

While the video plays in the Settings window, I noticed far less GPU usage
![Taskmgr_sTlDYYtoQf](https://user-images.githubusercontent.com/10728085/78773977-e81f4580-798b-11ea-86a4-7d73521eb018.png)
Even though it was using the same GPU (Integrated graphics), the settings window was using Video Decode rather than 3D processing. This is way smoother and has no hiccups at all.

Hopefully this helps you find a solution!

**Comment by MadNBG** [comment]
Office-PC: stuttering videos. Played the cached files with VLC or Mediaplayer: everything is fine. Sounds like an ugly deep problem..

**Comment by OrangeJedi** [comment]
Thanks for the screenshots; I they helped a lot. I did some tests of my own and Aerial is using larger than expected resources. Aerial does some processing on the videos to help with a few things.
I'm thinking I can add an option to tone down or disable the processing. That may help, I'll let you know what I find.

**Comment by prediscover** [comment]
I am also getting choppy playback when the screensaver activates. However when i click the preview function, it is smooth. In the video tab, it is also smooth. 

It's only when the Screensaver activates on its own it is choppy. 
My videos are cached.

Aerial Version
0.5.0

Additional context
Windows 10 v19608 build 19608
I have tried with and without the text overlay

**Comment by MadNBG** [comment]
OrangeJedi is actually working on it. In branch 0.5.2 performance-improvements are listed. Be patient :-) ....

**Comment by OrangeJedi** [comment]
@MadNBG is right, [v0.5.2](https://github.com/OrangeJedi/Aerial/releases/tag/v0.5.2-beta) has some massive performance improvements; Aerial should use at least half as much power now. Let me know if this solves everyone's issues. 

If you are still having problems you can go into the playback tab and click `disable all video processing`. It turns off a whole bunch of features and might not look as good, but it should use less power

@prediscover I saw this issue in my testing too. Do you have any other screensaver settings on like 'On resume, show lock screen'? Let me know if this update helps out.

**Comment by prediscover** [comment]
Yup @OrangeJedi . Just upgraded to 0.5.2 from 0.5.1 without changing any settings and it's smooth now. For what it's worth, I do have On resume, show lockscreen on.

**Comment by MadNBG** [comment]
yes, great success. Here, on integrated IntelGraphic, there is only a bit stuttering. Also, I hear the fan powering up, I guess showing the video is heavy on CPU/GPU. (I can't look in the taskmanager - only one display attached. It's a not powerfull PC.) 
Why is there a processing on the movies? Because of the corner-texts maybe?  
 
Someone mentioned a black playback - that problem seems to be gone too.
v0.5.2

**Comment by tech189** [comment]
Seems to be completely fixed for me too - everything is smooth now :D

**Comment by OrangeJedi** [comment]
Glad to hear everything is working!
For the record, the video processing's biggest feature is the fade transitions. It also helps with scaling to different resolutions and non 16:9 screens, as well as (I think) displays the video better. But yeah, the text should still work without it.
