### ISSUE TITLE
Screensave doesn't stop by any button press

### ISSUE THREAD

**Issue by VasilisPat** [OrangeJedi/Aerial#100]
**Describe the bug**
Screensaver does not terminate after any keyboard or mouse press.

**Expected behavior**
Terminate aerial on any button press, mimic Window's screensaver action.

**Aerial Version**
Aerial v1.0.0

**Comment by OrangeJedi** [comment]
Ouch. I've seen this happen once or twice on my computer after I released v1.0.0, but it doesn't happen consistently. Have you been able to consistently reproduce the error?

**Comment by VasilisPat** [comment]
Yes, alomst every time. The only way to exit seems to be alt+f4 or windows+d.

**Comment by OrangeJedi** [comment]
I'm going to try to re-produce the error on my end. Do you have the lock computer after running setting turned on? Have you opened an Aerial preview window since the last time Aerial was started?

**Comment by VasilisPat** [comment]
No, the lock computer option is left disabled and preview wasn't opened.

**Comment by OrangeJedi** [comment]
Okay, there was definitely an issue where if the preview windows was opened and the screensaver started up later that Aerial wouldn't quit. I added the code to fix this in the [v1.0.1 branch](https://github.com/OrangeJedi/Aerial/tree/v1.0.1), but I don't know if that was the specific issue. If you have a node.js environment setup you could test this yourself.

If you quit Aerial (right click on the tray icon, then restart the program) and then immediately start the screensaver via the tray menu does the issue still happen?

**Comment by VasilisPat** [comment]
Tried exiting the application and restarting Aerial without running preview. When the screensaver automatically kicks in, sometimes any keypress would stop the playback but other times it would act as if nothing happened. So I think that running the preview had some association with it, but there is something else too hiding underneath.

**Comment by OrangeJedi** [comment]
Thanks! I fixed the preview patch in [v1.0.1](https://github.com/OrangeJedi/Aerial/releases/tag/v1.0.1) and added a few small changes decrease the likelihood of this happening. Let me know if updating Aerial fixes the issue!
