### ISSUE TITLE
Screensaver starting when Windows are suspended

### ISSUE THREAD

**Issue by VasilisPat** [OrangeJedi/Aerial#105]
**Describe the bug**
Screensaver appears to be running after Windows are put to sleep and turned on again. As soon as I login the screensaver seems to be already running, as I notice that the video that is playing is not at its start.

**To Reproduce**
1. Put Windows to sleep
2. Powen on and login
3. Observer the screensaver running

**Aerial Version**
Aerial v1.0.1

**Comment by OrangeJedi** [comment]
I've seen this happen on my system and have a few ideas why it could be happening. I'll take a look at it and see how easy it will be to fix. 

Just to be clear though as soon as you press a key or wiggle a mouse Aerial closes?

**Comment by OrangeJedi** [comment]
Turns out Aerial would run itself even when the computer was sleeping! That's why you would see it after waking the computer back up. 

I added the code to  fix it to the v1.0.2 branch.

**Comment by VasilisPat** [comment]
Updated to v1.1.0 and the bug seems to still exist.
