### ISSUE TITLE
An option to force 4k for a 1440p display

### ISSUE THREAD

**Issue by Nit3H8wk** [OrangeJedi/Aerial#107]
**Is your feature request related to a problem? Please describe.**
It is not really a problem just 1080p looks a bit blurry on a 1440p monitor

**Describe the solution you'd like**
A setting to force 4k sized to a 1440p display similar to how you can set youtube to 4k on a 1440p display

**Describe alternatives you've considered**
I have tested it with wallpaper engine and it works however wallpaper engine always starts with the same video and cannot do random

**Additional context**
With the same 16:9 aspect ratio it should theoretically be possible.

**Comment by OrangeJedi** [comment]
Hi @Nit3H8wk! Thanks for using Aerial. Unfortunately for us, the Apple 4k videos are in an h.265 codec and can't currently be played with the HTML technology Aerial uses. What you can do (and what I and others have done) is convert the h.265 videos to a h.264 and replace them in the cache. See #17 for more information and some instructions. You could also downscale the videos to 1440p to save space! 

Hopefully this helps! And hopefully Aerial can support native 4k sometime in the future.
