### ISSUE TITLE
Javascript error on app open

### ISSUE THREAD

**Issue by dannya** [OrangeJedi/Aerial#108]
Just installed v1.0.1 and getting the following error dialog (can't copy the text out of it, sorry!):

![image](https://user-images.githubusercontent.com/394687/195559563-d60c7beb-521b-4cfa-89c1-590ed3af3903.png)

**Aerial Version**
1.0.1

I had a version installed previously, but have also tried an uninstall and reinstall (though the video cache folder remained, so not sure how thorough the uninstall actually was).

Please let me know if you need any more detail or system information.

**Comment by dannya** [comment]
A manual cleanup after uninstall (deleting the `C:\Users\danny\AppData\Roaming\aerial` directory seems to stop the issue happening.

**Comment by SquaredCircle84** [comment]
Similar thing happened to me.  Like dannya said, a complete uninstall/reinstall did the trick for me.

**Comment by OrangeJedi** [comment]
Hmm both this and #104 seem to be related to Aerial not loading new data after the update correctly.

@dannya what version of Aerial were you updating from?

**Comment by dannya** [comment]
@OrangeJedi I don't know for sure what the previous version was, but it is likely to be [Beta 0.5.4](https://github.com/OrangeJedi/Aerial/releases/tag/v0.5.4-beta)

**Comment by OrangeJedi** [comment]
I look at the code and this seems to be a problem with Aerial reading an old or corrupted config file after updating. When you updated Aerial did the app open the configuration window with a welcome message?

I'm going to look into what could cause the app to not get the correct data from the config file after a re-install.

**Comment by Jarves020** [comment]
Hi,
i have the same Problem here.
Updated from Beta v0.5.4 to v1.0.2
![image](https://user-images.githubusercontent.com/47521386/200167083-1652dd45-dce1-40f9-ab29-e89075a86fa2.png)

**Comment by OrangeJedi** [comment]
It doesn't seem like there is much I can do to fix this as it seems to be a problem with ` v0.5.4`'s code. Because future updates aren't effected I am going to close this out. If an error like this occures upgrading from a `v1.x.x` version, please create a new issue.
