### ISSUE TITLE
Virus on Windows security scan/smart screen not allowing .scr to be installed

### ISSUE THREAD

**Issue by freddy1407** [OrangeJedi/Aerial#11]
Tested v.5
Windows Security still not let me install the scr-File.
Windows 10 is deleting that File after unpacking zip when im trying to Install it.
Sorry for reopening.
Thanks!

**Comment by OrangeJedi** [comment]
You're fine opening this issue, it appears to be different from #6, you seem to have gotten aerial downloaded. I'm not entirely sure why windows is deleting the file, but you should be able to find a way to prevent it from being deleted somewhere online.
