### ISSUE TITLE
Error in v5.

### ISSUE THREAD

**Issue by freddy1407** [OrangeJedi/Aerial#12]
As someone else described in one of your closed issues, there is a new Error while Screensavers are not working :(

![E38FE137-F821-401A-87D2-56678249FEF4](https://user-images.githubusercontent.com/34100854/78646795-e422f300-78b9-11ea-9620-97f81357d01c.jpeg)
 
![763E063A-1D00-4E07-AEA3-50878D844A64](https://user-images.githubusercontent.com/34100854/78646790-e1280280-78b9-11ea-941f-24ad56fdebc6.jpeg)

**Comment by MadNBG** [comment]
Here it is starting, but under "Videos" there is nothing.

**Comment by OrangeJedi** [comment]
Yikes.
I found the error though. Basically the first time you install it Aerial initializes some variables and stores them. Because you only upgraded, not a first time install, the variables weren't initialized, hence the error.

I'm working on a fix that should be out later today.

**Comment by OrangeJedi** [comment]
I think I fixed it. Download and install [v0.5.1](https://github.com/OrangeJedi/Aerial/releases/tag/v0.5.1-beta), it shouldn't throw an error. Thanks for bringing this to my attention, let me know if you continue to have problems.

**Comment by freddy1407** [comment]
youre very fast man! thanks a lot!

at first: Error is not showing up again.
in Config, Videos are back listed and marked for download.

im sorry, but i have to report another problem:
after installed, i tested it and Screen just turns Black and stays Black for Minutes  :/

Could you build in an Indikator where every user can see informations about running downloads?
So, that i can check, when the first Video is fully downloaded.
in my Case i waited for downloads more than 6 hours. Screen still turns black.

thanks a lot!

**Comment by MadNBG** [comment]
Maybe i have the same as freddy. not shure, If it only occurs after a while (video change?) Actually I just woke up the screensaver: black screen but texts where shown.) I will do further checks. 
Yes, orangejedi is really fast. He should have a donate button..

**Comment by OrangeJedi** [comment]
I had I bit of a problem with this myself. If you try switching the videos with the arrow keys will it eventually play a video? Also, if you have the cache turned on clicking the 'update cache' button _might_ fix it.

I'll try to figure this out as soon as I can. If you send me screenshot of your errors it might help. If you run Aerial from the command line like this `aerial.scr /t /dt /nq` it will open Aerial in a smaller window with a console open. Any errors should be logged out.

As for a downloading indicator, I take a look at building one. For now you can look at the cache size indicator (the videos average ~230 MB) or open the cache.

**Comment by MadNBG** [comment]
Fixed

**Comment by freddy1407** [comment]
Thats when i run it how u told me:

![CC7B456D-6477-4AC2-A82A-40F08CC0679A](https://user-images.githubusercontent.com/34100854/78827200-07958d00-79e3-11ea-8bc9-e176f1b06101.jpeg)


After installing, i updated Cache and used
Right arrow to skip Blackscreen - and then finally, the first time a Video started to play!!!
Thanks soooo much!

**Comment by OrangeJedi** [comment]
No thank you, that screenshot helps a lot. Glad to hear updating the cache worked. I think there is a problem with Aerial's list of cached videos. I'll try working on a fix.
