### ISSUE TITLE
3 Aerial applications in Windows System Tray

### ISSUE THREAD

**Issue by zanovis** [OrangeJedi/Aerial#121]
**Describe the bug**
There are 3 Aerial icons in the W10 System Tray (bottom right of screen)

*edit* there are also 10 Aerial.exe processes running in task mgr

**To Reproduce**
1. Run Aerial
2. Click the arrow to view your system tray
3. See error

**Expected behavior**
See 1 aerial app in sys tray

**Screenshots**
![image](https://user-images.githubusercontent.com/32601911/206885658-c59d95d7-95fc-42ba-afa0-c2626259d3a7.png)

**Aerial Version**
1.1.0

**Additional context**
N/A

**Comment by VasilisPat** [comment]
Have you tried manually killing all the processes and restarting Aerial? I remember this happening to me when I wanted to open the config menu. When clicking on the app, you are only running a new instance of it. If you want to open the config menu, right click the icon on the tray and select the option you want.

If this is not the case, please describe more in the depth the whole procedure to reproduce the issue (running apps, state of pc, etc).

**Comment by zanovis** [comment]
I think it was an artifact of trying to run the program multiple times. Seems to have resolved itself!
