### ISSUE TITLE
moving text to protect OLED screens

### ISSUE THREAD

**Issue by Leum-Dunn** [OrangeJedi/Aerial#124]
**Problem**
I use an OLED TV as my main monitor and need to protect it against burn in.
**Solution**
I'd appreciate an option to have the text randomly move from one location/corner to another every [x-many] seconds
**Alternatives**
I currently avoid using the text display option

**Comment by OrangeJedi** [comment]
That's a great feature to add, considering that this was the whole point of screensavers once. I'll add it to the project and work on it as soon as I get back to working on Aerial. Thanks for the suggestion!

**Comment by Leum-Dunn** [comment]
Thanks for adding the functionality - really appreciated
