### ISSUE TITLE
Are there any command short cuts for Aerial?

### ISSUE THREAD

**Issue by ZaViper** [OrangeJedi/Aerial#127]
I would like to create an automation using Eventghost to trigger the screen saver of Aerial and was hoping there was a command shortcut to make this happen. Like when I make a shortcut for Firefox and attach  --start-fullscreen at the end it will load in full screen.

**Comment by OrangeJedi** [comment]
If you are talking keyboard shortcuts see #122.

If you are talking about starting Aerial using command arguments see [this](https://github.com/OrangeJedi/Aerial/wiki/Contributing-Guide#start-up-flags) part of the wiki. `aerial.exe \s` should run the program in full screen mode.
