### ISSUE TITLE
24h time format

### ISSUE THREAD

**Issue by MadNBG** [OrangeJedi/Aerial#13]
v.0.5.1
Text (clock) is in 12h format. A format like the systems time format would be nice. (I'm using 24h format..)

Hey, thanks, great work, there is no much negative left..

**Comment by OrangeJedi** [comment]
Hi, I'm glad you're enjoying the project. Aerial uses a string to determine how to display the time. Its the `hh:mm:ss` thing on the date/time option. If you replace the `hh` with `HH` the clock will show in 24 hour time. You can click the "show formatting details" button or read [this](https://momentjs.com/docs/#/displaying/) for other date/time display options. 

I should probably make that more obvious, maybe add a menu to select presets from.

**Comment by MadNBG** [comment]
Yeah! Everything is in! Thanks!
