### ISSUE TITLE
Error when Windows 10 start

### ISSUE THREAD

**Issue by aoxu** [OrangeJedi/Aerial#131]
**Describe the bug**
An error occurs when Windows 10 starts.

**To Reproduce**
1. Windows starts. This error occurs every time. Easy to reproduce.

**Expected behavior**
No error.

**Screenshots**
![image](https://user-images.githubusercontent.com/3169925/219823616-9bc2067b-d1ee-413b-8a42-eac5806bbf8a.png)

**Aerial Version**
1.1.0

**Additional context**
None.

**Comment by OrangeJedi** [comment]
This appears to be an error with the auto update script. The app is trying to reach a file (`https://github.com/OrangeJedi/Aerial/blob/master/app.js`) and can't load it. Other than this error does the app work as expected?

**Comment by aoxu** [comment]
Yes, the app works every time as expected. I can access that URL in a browser. 

Maybe it's a network issue, could the app ignore the error and just write the error information in the log?

**Comment by OrangeJedi** [comment]
Yep! That app should be ignoring the error and continuing on, I'll add a fix in the next release.

**Comment by aoxu** [comment]
I tried to launch Aerial when 5 minutes after system started, I'm sure the network is ready, but the error showed every time.

**Comment by OrangeJedi** [comment]
This is now fixed in v1.2.0. Aerial won't alert you if it can't assess the internet.
