### ISSUE TITLE
Bug when "Start Aerial after X minutes" is set to 0

### ISSUE THREAD

**Issue by sebekhtc** [OrangeJedi/Aerial#136]
**Describe the bug**
So I wanted to disable temporarily the screensave to watch a web streamed movie. Coulnd't find anything so I tried set to start Aerial after 0 minutes/

**To Reproduce**
1. Go to 'Config' / Start Aerial After _  minutes
2. Change minutes to '0.'
3.  Close window to see the error

**Expected behavior**
A clear and concise description of what you expected to happen - for me expected would be disabling the aerial

**Screenshots**
![obraz](https://user-images.githubusercontent.com/5500978/224873659-c2392413-e0a9-499c-9327-34b8d41eae05.png)

**Aerial Version**
1.2.0

**Additional context**
Add any other context about the problem here: changing the negative values results in same bahavior

**Comment by sebekhtc** [comment]
Don't want to open a feature request case, if you can make '0' minutes disabling the aerial.

**Comment by OrangeJedi** [comment]
If you right click on Aerial's tray icon you will see menu options to suspend (or disable) Aerial. You can do this indefinitely, or for 1 or 3 hours. Hopefully that helps you for your use case. 

As for the error when setting Aerial to start after 0 minutes, that is a bug that can be fixed. I'll added to our project board.
