### ISSUE TITLE
Custom Videos dont work

### ISSUE THREAD

**Issue by tommyw1979** [OrangeJedi/Aerial#137]
I am trying to load custom video folders, but when I select the folder, it does not register it. the videos are all MOV files.

**Comment by OrangeJedi** [comment]
Looking at this, that sounds right. Aerial need videos to be in a web supported format (.mp4, .webm, .ogv). Some .mov files will work without converting them if you change the extension to .mp4, but that isn't guaranteed. 

I will hopefully be improving the documentation soon and this will definitely be included in it.
