### ISSUE TITLE
Screensaver starts while watching movie on VLC

### ISSUE THREAD

**Issue by gsbernstein** [OrangeJedi/Aerial#140]
**Describe the bug**
Screensaver does not respect playing media

**To Reproduce**
1. start a movie in vlc
2. wait for configured screensaver delay

**Expected behavior**
Movie should not be interrupted

**Screenshots**

**Aerial Version**
1.2

**Additional context**
Is it possible to use the native windows screensaver feature to control when the screensaver shows up? Seems hacky having a separate program trying to replicate that behavior.

**Comment by OrangeJedi** [comment]
See #114, this is a known issue. Lots of people were seeing massive performance hit when running as a native Windows screensaver (#36), hence the switch to the launching application. 

[This comment](https://github.com/OrangeJedi/Aerial/issues/114#issuecomment-1466375815) has instructions on how to run Aerial as a native screensaver if you want (it is fairly easy), or you could use the `suspend` option in the system tray menu. I am currently looking at options to make this smoother in the future.

**Comment by gsbernstein** [comment]
Well apparently it also starts while playing VR. And it goes into a deeper sleep than my computer normally does. Unfortunately I'm gonna have to switch back to @cdima's version

**Comment by gsbernstein** [comment]
Thank you! Works great, no performance issues, respects all the configuration, and the settings button works to launch your custom config. Was just a little tricky because cDima's version was still there so at first it was unclear if it had actually replaced it or not, but I deleted the old one and renamed the new one and it worked.
