### ISSUE TITLE
Settings from Windows Screen Saver Settings not launching settings

### ISSUE THREAD

**Issue by EranBoudjnah** [OrangeJedi/Aerial#149]
**Describe the bug**
When trying to access the app settings via Screen Saver Settings, the app launches into the system tray, and the settings dialog doesn't show.

**To Reproduce**
1. Launch Screen Saver Settings
2. Make sure Aerial is selected
3. Click on "Settings..."
4. Observe Aerial launches into the system tray, the setting dialog never shows

**Expected behavior**
The settings dialog of Aerial shows when clicking on "Settings...".

**Aerial Version**
What version of Aerial are you running?
1.2.0

**Comment by OrangeJedi** [comment]
Are you following the instructions in #114 and using Aerial as an .scr? And is the `Auto launch from system tray` setting disabled on the advanced tab in the settings?
Let me know and I can take a further look into it.

**Comment by OrangeJedi** [comment]
After some testing this is expected behavior when `Auto launch from system tray` is still clicked and Aerial is launched as a `.scr`.

If you download the `.scr` file in the latest (`v1.2.1`) release that option will be disabled and the settings menu will work as expected.

**Comment by EranBoudjnah** [comment]
Works perfectly, thank you!
