### ISSUE TITLE
Folder path for cache

### ISSUE THREAD

**Issue by Aleatoire** [OrangeJedi/Aerial#15]
HI, thanks for your work.
Can you add a variable in the video cache settings to set the cache folder path ? 
Thanks you :)

**Comment by tech189** [comment]
I was just about to ask for this too haha, this would be greatly appreciated because I have a small SSD for Windows and then a larger HDD with plenty of space for the cache :)

**Comment by OrangeJedi** [comment]
Yeah, I was thinking about this the other day. Definitely worth putting in. I'll put any updates here.

**Comment by AdriaanDeVos** [comment]
Thanks for your hard work OrangeJedi! Great to see an Electron re-release of this screensaver I have been running for years now.

Having the ability to change cache directory for the videos is a must-have for me. Looking forward to the 0.5.2 release so I can start using your very improved version of this epic screensaver. 😄

**Comment by OrangeJedi** [comment]
Added in [v0.5.2](https://github.com/OrangeJedi/Aerial/releases/tag/v0.5.2-beta). Let me know if there are any issues.

**Comment by AdriaanDeVos** [comment]
Looks to work on my end! Videos appear in my indicating cache location folder. Thank you for this feature request and the solid work! 💪

**Comment by tech189** [comment]
Working well for me too! Thanks again
