### ISSUE TITLE
Screensaver shows under other apps

### ISSUE THREAD

**Issue by swanlon** [OrangeJedi/Aerial#158]
When screensaver starts, it runs under certain programs like MyDockFinder, for example. Would be cool if it could run on top of everything
![dwadawdwa](https://github.com/OrangeJedi/Aerial/assets/79228923/06ab98cf-eab1-4d96-8195-34f80483c7d9)

**Comment by OrangeJedi** [comment]
I think you may have the wrong repository. OrangeJedi/Aerial is only supported for Microsoft Windows. For Apple's MacOS please use [JohnCoates/Aerial](https://github.com/JohnCoates/Aerial).

**Comment by swanlon** [comment]
> I think you may have the wrong repository. OrangeJedi/Aerial is only supported for Microsoft Windows. For Apple's MacOS please use [JohnCoates/Aerial](https://github.com/JohnCoates/Aerial).

I appreciate the compliment but it is indeed Windows. The program was having an issue with MyDockFinder but at least for me (on newest version and some specific settings, I don't think that bug occurs anymore. If it does for anyone else though, feel free to share
