### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by tech189** [OrangeJedi/Aerial#16]
'Open cache in file explore' should say 'Open cache in File Explorer'
https://github.com/OrangeJedi/Aerial/blob/b9a8b98412f320e18aa63ae7798c448cfdad5308/web/config.html#L102
![aerial scr_2SQGY833Y6](https://user-images.githubusercontent.com/10728085/78775099-924b9d00-798d-11ea-8709-23b1191e07f0.png)

**Comment by OrangeJedi** [comment]
You're right, I'll put this in for the next update.

**Comment by OrangeJedi** [comment]
Released in [v0.5.2](https://github.com/OrangeJedi/Aerial/releases/tag/v0.5.2-beta)
