### ISSUE TITLE
Love it when it works. I get these types of errors all the time.

### ISSUE THREAD

**Issue by madman2012** [OrangeJedi/Aerial#160]
**Describe the bug**
Will not run.

**To Reproduce**
When the screen saver tries to run I normally get a java error like this. 

**Expected behavior**

**Screenshots**
![Screen Saver Error](https://github.com/OrangeJedi/Aerial/assets/5844691/01bc3b9b-f0f7-4b9c-8e35-15b616cc935f)

**Aerial Version**
LATEST

**Additional context**

**Comment by kloodhu** [comment]
same here.

**Comment by skbtwiz** [comment]
Can confirm, same is happening with latest update.

**Comment by grendizerus** [comment]
I have the same problem I'm on v1.2.1

**Comment by OrangeJedi** [comment]
Duplicate of #143. I've been digging around I think I found the source of this bug. Hopefully a fix fill come soon.
