### ISSUE TITLE
4K Support?

### ISSUE THREAD

**Issue by JesperKarlsson** [OrangeJedi/Aerial#17]
Can I choose to play all videos in 4K?

**Comment by OrangeJedi** [comment]
Due to they way Aerial plays videos (which, in turn, is due to the framework it uses) and the encoding Apple uses on its' 4K videos we cannot play them.
It is however possible to download the 4K (SDR) videos from [here](https://aerial-screensavers.netlify.com/) and convert them to .mp4 (H.264) and replace the videos in the cache with the 4K versions. I've actually been doing this myself and it works fine. I might write out some instructions in the future if there is enough interest.

**Comment by JesperKarlsson** [comment]
Thank you for detailed answer, and great work so far!
I will say that the interest of making 4K playable is good enough, according to 4K-standard on monitors theese days. But I understand if you have more important things to improve in the software first! I would still appreciate a guide for this! :)

**Comment by OrangeJedi** [comment]
Yeah, I've taken a look at what I would have to do to add in native 4K support and decided that, for now, it isn't feasible. I might come back to it sometime in the future though. 
I'll see if I can get a guide up sometime soon. It would basically be a more detailed walk through of simple instructions above. I comment here once I do.

**Comment by JesperKarlsson** [comment]
Thanks! :)

**Comment by dennischen0** [comment]
@OrangeJedi What were your parameters for converting from hevc to h.264?

**Comment by OrangeJedi** [comment]
I used [Adobe Media Encoder](https://www.adobe.com/products/media-encoder.html), but I believe [Handbreak](https://handbrake.fr/) or another similar program would work too. You need to download the 4K video from the [above link](https://aerial-screensavers.netlify.com/) and convert the file to a h.264 encoding. You can lower the bitrate for a smaller file size. It will come out as an .mp4 file, you'll need to rename it to the name of the cached file with a .mov extension and replace it. 

I really need to write our these instruction in markdown with pictures. I'll get around to it eventually...

**Comment by Krakyn** [comment]
Just commenting to agree with what others have said - 4k support would definitely be very much appreciated. Unfortunately the screensavers look really bad on any 1440p or 4k monitor, which are extremely common nowadays. 

Anyway, thanks for your hard work. Your Aerial is so much better in functionality than the other Windows version which hasn't been updated in forever. I just wish I could use it on my monitor! It's a shame that we can't have things as good as the Mac users.

**Comment by apocolipse** [comment]
Hey @OrangeJedi I'm just now finding this project after deciding to update from my aging matrixGL screensavers (lol).   I was wondering if you'd looked into https://github.com/strukturag/libde265.js for HEVC/HDR playback?  I'd love to have full HDR playback on my new laptop (Razer Blade w/ 4K OLED) ;)  I've some free time right now (like most people) so I may dig in and see if I can add myself :)  I'm currently downloading all vids and rigging up a script for download/convert to h264

**Comment by OrangeJedi** [comment]
@apocolipse That look great! I spend a small amount of time looking for something like this, but I decided to table it until I finished some other stuff. I'll definitely take a look at implementing it. 
If you want to help out that would be great, I'm always looking for help on this project.

**Comment by apocolipse** [comment]
@OrangeJedi yeah I’ll def take a look, though js isn’t my forté.  After converting all the videos and seeing 30gb go to 120gb with similar bitrates from h.265 to h.264, playing the former would be better lol.

Also I noticed both 1080p and the 2160p videos stuttering a bit during playback, it went away when disabling processing.  Downloading transcoding and renaming took all day (with nvenc on a 1080 ti even) but totally worth it.  Gorgeous on my 27” 4K display and especially my 15” laptop 4K

**Comment by OrangeJedi** [comment]
Yeah, that's video encoding for you. To be honest though, encoding seems to take more CPU than GPU usage. I did convert some videos myself, but only the ones I really wanted because of the large file size and long covert time.

Don't stress to much about implementing it yourself, especially if your going out of the way. I'll implement sometime, but I can't make any guarantees about when I'll get around to it.

**Comment by kastov** [comment]
Hello anyone!
I read all posts. And I want all videos in 4K. But it is too much files and unfortunately I don't have a lot of time for this.
And all files I should rename.. It is not so easy.

Anyone have all videos(or maybe 50% of this) in 4K, mp4(h.264)?

**Comment by dennischen0** [comment]
I wrote a script to do the renaming for you if you have all the files already.

[aerial_parser](https://github.com/dennischen0/aerial_parser)

**Comment by kastov** [comment]
Thanks a lot dennischen0! I renamed all files and next task is convert them.
I'm going to convert all 98 videos from mov(4K), to MP4(H.264)!

**Comment by kastov** [comment]
After converting I zip it and share with u.
I think it will be about 30-40GB.

**Comment by arsalan86** [comment]
@kastov have you converted the videos? I'd like them too, please. I can share a onedrive folder where you can upload them, if you need one.

Thanks

**Comment by kastov** [comment]
@arsalan86 yep, I convert all of them. 

U can download it from [here](https://mega.nz/folder/nWhUAYCT#7HyJqZdSPhxrr-mT5gR0_Q)

I recommend that you first download all 1080P videos (from the program!) that are included in the program. After all the videos are downloaded and will be located in your folder. You must use the" Replace files " to put them in the folder where you previously downloaded 1080P videos.
I did not work otherwise, only through replacing files. Otherwise, the program will overwrite 4K files to normal 1080P video.

**Comment by HeLiOn--PrImE** [comment]
hello guys.
would the new videos work if I just download the 1080 versions from [here](https://aerial-screensavers.netlify.com/) and add them to the cache folder? 

Or... do I need to rename them?

**Comment by OrangeJedi** [comment]
If you copy all the 4K videos into the cache you shouldn't need to have the normal videos downloaded. You will need to click the "Update Cache" button in the UI though.

**Comment by HeLiOn--PrImE** [comment]
ok, my question isn't related to 4k support. I forgot the discussion I was visiting. For that I apologize.
My question is strictly about the 1080p videos. I want to add the new videos since my version doesn't seem to have kept up with the content. Can we continue this here, or should I start a new discussion?

**Comment by OrangeJedi** [comment]
Lets start a new issue for this and keep all 4K discussion here.

**Comment by 6illess** [comment]
@kastov Thank you very much for sharing the 4K videos. Works like a charm.

**Comment by Krakyn** [comment]
@kastov Thanks for sharing that download link! FYI, I believe you accidentally included three videos that are 1080p (not 4K). Their video IDs begin with 9CCB8297, D5E76230 & B876B645.

**Comment by christiaan109** [comment]
Thanks @OrangeJedi for creating this screensaver! And thanks to @kastov  for sharing the 4k versions!!

**Comment by Sarcas666** [comment]
Just sharing some info; the [open-source MacOS version](https://aerialscreensaver.github.io/index.html#features) now includes some free 20 third-party 4k videos from [these ](https://www.jetsoncreative.com/aerial) guys.

**Comment by Kraiggers** [comment]
> @kastov Thank you very much for sharing the 4K videos. Works like a charm.
> 

> If you copy all the 4K videos into the cache you shouldn't need to have the normal videos downloaded. You will need to click the "Update Cache" button in the UI though.

Hello friends.  Thanks @orangejedi. I'm coming pretty late to this party... I downloaded the 4k videos from the netlify web link, 4k SDR with .mov extension. The app downloads 1080p files into the cache. I tried renaming and replacing the 1080p files with 4k files and the app refuses to pick them up. It will only show the three remaining 1080p files. 

Do I need to rip the 4k files to h264? (They appear to be h264 already? I can change the extension to mp4 and they work the same?)

Or should I download the files from #kastov?

Any advice to get 4k working would be greatly appreciated...

Cheers, kraig.

**Comment by ThinkSalat** [comment]
I thought the videos didn't look as sharp as on my apple tv! This explains it. 

Here's all the 4k-hdr links: https://pastebin.com/kQp96gfh

Here's all the 4k non hdr links: https://pastebin.com/aR265ge8

In case it gets updated you can run this scraper yourself in the console of the window. It copies the contents to your clipboard. Of course you can modify to your liking:

copy 4k hdr links to clipboard:
 `copy([...document.querySelectorAll('a')].filter(el => el.innerHTML.includes('4K-HDR')).map(el => el.href).join(', '))`
copy 4k sdr links to clipboard:
`copy([...document.querySelectorAll('a')].filter(el => el.innerHTML.includes('4K') && !el.innerHTML.includes('HDR')).map(el => el.href).join(', '))`

@dennischen0 I'm unable to get your script to work, - first didn't realize I'd have to npm install - should add that to your readme. ALso I'm getting some "spawnSync" error that i can't parse - coming line 32 and 20 of parsejson.js

**Comment by ThinkSalat** [comment]
> @arsalan86 yep, I convert all of them.
> 
> U can download it from [here](https://mega.nz/folder/ab4nXTiD#ZDy9akTE25i-0UGmAIgjKw)
> 
> I recommend that you first download all 1080P videos (from the program!) that are included in the program. After all the videos are downloaded and will be located in your folder. You must use the" Replace files " to put them in the folder where you previously downloaded 1080P videos. I did not work otherwise, only through replacing files. Otherwise, the program will overwrite 4K files to normal 1080P video.

This is downloading at less than 3g speeds for me. It's been running for several hours and is at 18%. I also don't have a mega account or plan to make one. Can you downlaod this without logging in/buying a subscription?

**Comment by Sarcas666** [comment]
I have the Microsoft HEVC extension from the store installed. It says 'works with every video player'. Would Aerial be able to use it to play the 4k/HDR files somehow?

**Comment by OrangeJedi** [comment]
> I have the Microsoft HEVC extension from the store installed. It says 'works with every video player'. Would Aerial be able to use it to play the 4k/HDR files somehow?

I want to say that I tired that I while back and it didn't work, but I'm not 100% sure on that. You can try it yourselves by replacing the video file in the cache folder with a h.256 video and seeing if it loads on the video tab in the configuration window.

As an FYI, Aerial is an [Electron](https://www.electronjs.org/) app and uses an HTML `<video>` tag to play video.

**Comment by Sarcas666** [comment]
I've created a profile with only one video selected (the top one, Africa and the Middle-East), looked up its ID in the Video Info Editor (2F72BC1E-3D76-456C-81EB-842EBA488C27), looked up the corresponding 4k/HDR version (comp_A013_C012_0122D6_CC_v01_HDR_PS_FINAL_20180710_HDR_4K_HEVC.mov), deleted the file in the Aerial cache folder and copied and renamed the 4k/HDR file. Refreshed Aerial to be sure, restarted it, and... it seems to just work fine. So I guess it works... I'll need to manually match all files now, so I'll wait until a rainy day, but good to know. :)

**Comment by OrangeJedi** [comment]
I just checked and was able to get Aerial to play an HVEC/h.265 video without any fine-tuning. This is huge news; sometime in the past few years underlying support got added to something and now we can play 4K videos in Aerial! It shouldn't be too hard to add a toggle option to Aerial in the near future.

I don't know yet if everyone will be able to play them, or if you have to have the right extensions installed. I didn't intentionally install anything, but my PC might already have them. @Sarcas666 what version of Windows are you running?

**Comment by Sarcas666** [comment]
> @Sarcas666 what version of Windows are you running?

Windows 11 pro, up-to-date, with the official hevc codec from the Microsoft store. 

I read that Chromium (which Electron uses if I understood this right) has been silently updated to be able to play hevc html tags. Things. Files. Whatever it is :) So perhaps that is why it works now?

**Comment by OrangeJedi** [comment]
Yep. Taking a quick look at it between August to November of 2022 H.265 support (for OSs that support it) was added to Chromium and subsequently Electron. This should cover most users of Aerial, and certainly anyone who wants 4K. 

I'm super excited for this one because the H.256 files are much smaller than the H.264 ones. This is great for everyone, even those who won't use 4K video.

**Comment by Kraiggers** [comment]
ok, so what's the upshot?  Does this mean that 4k will be incorporated as a feature in a future (soon-ish) release?  I can wait if it's coming to a proper release…. :)

**Comment by Kraiggers** [comment]
Dude.  You must be more excited about this than I am... 🤣

**Comment by Kraiggers** [comment]
Any update on the status of this feature?  I'm still pretty pumped about it!  :)

**Comment by OrangeJedi** [comment]
I will try to get it out this week. I got the videos loaded and working in the app, but they seemed to cause issues with frame rate and transitions that I would like to fix before I release the update.

**Comment by Kraiggers** [comment]
Cool.  Thanks for the update.  Its not an emergency or anything; thanks for your continued efforts!

**Comment by Kraiggers** [comment]
Any update on the 4k release?

**Comment by OrangeJedi** [comment]
4K support has finally been added! One of our longest issues can be closed. Most systems should be able to playback 4K videos with no problems. Sorry for the long delay; I have had a crazy couple of months and just now had time to get this out.

Enjoy the 4K everyone!

**Comment by Kraiggers** [comment]
Thanks!!!  This is really cool and a very welcome feature.  👍

**Comment by Gaibhne** [comment]
@OrangeJedi that is awesome, thank you! I saw the added toggle to turn on 4K, but my video download folder did not change. What must I do to actually get the 4K videos, other than the toggle ?
