### ISSUE TITLE
Unable to use `settings` or `example` in windows screen protection settings screen.

### ISSUE THREAD

**Issue by AdriaanDeVos** [OrangeJedi/Aerial#19]
**Describe the bug**
Unable to use `settings` or `example` in windows screen protection settings screen.

**To Reproduce**
1. Download 0.5.2 zip release.
2. Unzip to folder with correct permissions.
3. Run aerial.scr
4. Configure my settings (like changing cache folder location).
5. Closing the application.
6. Opening Windows Screen Protection Settings.
7. Press `Settings` or `Example`.

**Expected behavior**
I expect that AerialJs shows the configuration screen when I press `settings` and have it show videos when I press `example`.

**Screenshots**
![image](https://user-images.githubusercontent.com/9716228/79666133-ed636800-81b5-11ea-8261-791027a5e5e0.png)

**Aerial Version**
Beta 0.5.2

**Additional context**
Running the application with `aerial.scr /t /dt /nq` works. Maybe document these parameters?
The only error I got was:

```(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397```

**Comment by OrangeJedi** [comment]
It seems like you were able to open the 'settings' menu earlier, is that correct?
Try running the application with `aerial.scr /c` or `aerial.scr /s` and see if 1) the Aerial opens and 2) if any errors appear in the command line.
Also, the message you got shouldn't be causing the problem.

**Comment by AdriaanDeVos** [comment]
The `settings` menu successfully opens when I double click the aerial.scr file. The buttons in the windows screen protection settings screen do not work on my end. The screensaver also does not run after my 5m inactivity.

`aerial.scr /c` successfully opens the configuration scherm without errors.

`aerial.scr /s` successfully opens the screensaver but returns this error when closed:
```
C:\Windows\System32\cmd.exe[188]: ../../third_party/electron_node/src/node_platform.cc:449: Assertion `data' failed.
 1: 00007FF645272CBA GetHandleVerifier+10829562
 2: 00007FF6447EA396 node::Abort+22
 3: 00007FF6447E9F93 node::Assert+131
 4: 00007FF6452768D7 GetHandleVerifier+10844951
 5: 00007FF645276B35 GetHandleVerifier+10845557
 6: 00007FF64302A0DE v8::Unlocker::~Unlocker+297758
 7: 00007FF64302E294 v8::Unlocker::~Unlocker+314580
 8: 00007FF64302A7B5 v8::Unlocker::~Unlocker+299509
 9: 00007FF64302A452 v8::Unlocker::~Unlocker+298642
10: 00007FF643025986 v8::Unlocker::~Unlocker+279494
11: 00007FF64308F880 v8::Unlocker::~Unlocker+713408
12: 00007FF642FF36E0 v8::Unlocker::~Unlocker+74016
13: 00007FF6430207E9 v8::Unlocker::~Unlocker+258601
14: 00007FF6430208ED v8::Unlocker::~Unlocker+258861
15: 00007FF642FF255A v8::Unlocker::~Unlocker+69530
16: 00007FF642FF0EB1 v8::Unlocker::~Unlocker+63729
17: 00007FF642FF3081 v8::Unlocker::~Unlocker+72385
18: 00007FF6431C2B77 v8::Platform::SystemClockTimeMillis+1010695
19: 00007FF6431C3913 v8::Platform::SystemClockTimeMillis+1014179
20: 00007FF642FD9658 v8::Unwinder::PCIsInV8+111096
21: 00007FF64300575A v8::Unlocker::~Unlocker+147866
22: 00007FF6432130BC v8::internal::OSROptimizedCodeCache::GetBailoutIdFromEntry+43420
23: 00007FF643212B54 v8::internal::OSROptimizedCodeCache::GetBailoutIdFromEntry+42036
24: 00007FF6432132B8 v8::internal::OSROptimizedCodeCache::GetBailoutIdFromEntry+43928
25: 00007FF642FDB364 v8::Unwinder::PCIsInV8+118532
26: 00007FF642F02816 v8::EmbedderHeapTracer::IterateTracedGlobalHandles+192470
27: 00007FF6430AEF22 uv_udp_get_send_queue_count+108882
28: 00007FF6431EB9AC v8::Platform::SystemClockTimeMillis+1178172
29: 00007FF6431EA670 v8::Platform::SystemClockTimeMillis+1173248
30: 00007FF6431E9DB4 v8::Platform::SystemClockTimeMillis+1171012
31: 00007FF64309C2A6 uv_udp_get_send_queue_count+31958
32: 00007FF6430A4FF5 uv_udp_get_send_queue_count+68133
33: 00007FF6437FE2FD v8_inspector::V8StackTraceId::ToString+2948173
34: 00007FF64386E634 v8_inspector::V8StackTraceId::ToString+3407748
35: 00007FF64378D578 v8_inspector::V8StackTraceId::ToString+2485960
36: 00007FF64378D578 v8_inspector::V8StackTraceId::ToString+2485960
37: 00007FF643786C39 v8_inspector::V8StackTraceId::ToString+2459017
38: 00007FF64378D578 v8_inspector::V8StackTraceId::ToString+2485960
39: 00007FF64378D578 v8_inspector::V8StackTraceId::ToString+2485960
40: 0000023E22F1E24A
```

**Comment by AdriaanDeVos** [comment]
I resolved this issue by removing the original cDima/Aerial screensaver from my PC and doing a clean-install of this update OrangeJedi/Aerial screensaver.

**Comment by OrangeJedi** [comment]
That makes sense. It was looking like it was a problem with Windows rather than Aerial. Glad you were able to resolve your issues!
