### ISSUE TITLE
Create markdown documentation indicating launch parameters

### ISSUE THREAD

**Issue by AdriaanDeVos** [OrangeJedi/Aerial#20]
**Is your feature request related to a problem? Please describe.**
Having the launch options more easily available allows more flexibility to the endusers. It also allows for easier debugging because people can open the error console.

**Describe the solution you'd like**
I would like to have a section in the README.md indicating the possible launch parameters and their effects. 

**Describe alternatives you've considered**
An alternate solution to this problem is to create a separate markdown documentation file indicating the possible launch parameters and their effects. Then only a reference to this separate file should be added README.md document.

**Additional context**

**Comment by OrangeJedi** [comment]
I believe the documentation you need can be found [here](https://github.com/OrangeJedi/Aerial/blob/master/CONTRIBUTING.md#how-to-set-up-aerials-dev-environment). I also updated the readme with more explicit information of what is in  CONTRIBUTING.md.

**Comment by AdriaanDeVos** [comment]
That is indeed what I was looking for. Thanks!
