### ISSUE TITLE
Add SourceMap to project for easier Devtools usage

### ISSUE THREAD

**Issue by AdriaanDeVos** [OrangeJedi/Aerial#21]
**Is your feature request related to a problem? Please describe.**
Keep your client-side code readable and debuggable even after you've combined, minified or compiled it. Use source maps to map your source code to your compiled code.

**Describe the solution you'd like**
I would like to have a DevTools compatible SourceMap in `./resources/app/web/uri.all.js.map`. This makes it easier to develop and maintain the code.

**Describe alternatives you've considered**
This should have a low priority and should only be considered if current contributers or testers use the DevTools application.

**Additional context**
Documentation:
https://developers.google.com/web/tools/chrome-devtools/javascript/source-maps

**Comment by OrangeJedi** [comment]
This is a good idea. Your are right in that it is lower priority, but I'll put it on the back-burner and start working on it.
