### ISSUE TITLE
Videos list scrollbar goes out of bounds

### ISSUE THREAD

**Issue by tech189** [OrangeJedi/Aerial#25]
**Describe the bug**
In the Videos tab of the Settings application, the scrollbar for the list of videos on the left goes out of reach, see the gif below

**To Reproduce**
1. Open the Settings
2. Click on Videos
3. Use the scrollbar all the way to the bottom

**Expected behavior**
It should stop when it hits the edge of the window

**Screenshots**
![test (1)](https://user-images.githubusercontent.com/10728085/79734295-64038100-82ee-11ea-9f51-2ea8e69eeb5f.gif)

**Aerial Version**
0.5.2

**Comment by OrangeJedi** [comment]
This is a know (but overlooked) issue. I'll definitely take a look at it; it really should be fixed.

**Comment by OrangeJedi** [comment]
I've fixed the issue for the next release. It was some messy display height stuff, but it is fixed.

I'll close this issue when the patch is released.

**Comment by OrangeJedi** [comment]
Fixed in [v0.5.3](https://github.com/OrangeJedi/Aerial/releases/tag/v0.5.3-beta). Let me know if you have any trouble.
