### ISSUE TITLE
Not Playing on Bootcamp

### ISSUE THREAD

**Issue by john2691** [OrangeJedi/Aerial#27]
I get a blank screen in both preview and the actual screen saver, is there a reason this wouldn't work while running Windows in Bootcamp?

**Comment by OrangeJedi** [comment]
I don't see why it wouldn't work because of Bootcamp...

Can you open the screensaver settings window? 
Can you preview any of the preinstalled screensavers?

**Comment by john2691** [comment]
Yes, playing the videos in the settings screen works just fine. Another thing I just noticed, when I check the "Disable All Video Processing" box, the preview will not show a black screen, it just stays on the current view of the desktop.

**Comment by OrangeJedi** [comment]
Using the "Disable All Video Processing" switches the video player, so the black v. transparent window makes sense. It seems to be a problem with the videos loading, though it is curious that they play fine in the settings window. 

Try running `aerial.scr /t /dt /nq` in command prompt in the location of the `aerial.scr` file. It should open the screensaver in a smaller window and as well as a console that should log any errors. If you could screenshot or copy any errors you get that would be super helpful.

**Comment by john2691** [comment]
Ok, I now see a still screen of one of the videos, which begins playing after about 1 minute, and this shows up in the console.

> DevTools failed to parse SourceMap: file:///C:/Users/John/Downloads/aerial-v0.5.2/aerial-v0.5.2/resources/app/web/uri.all.js.map

**Comment by john2691** [comment]
FWIW, the command line also show the following after exiting the preview window.

> (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397

**Comment by OrangeJedi** [comment]
Both or those messages aren't related to the problem. You say the video starts playing after a minute or so? Could it be an issue related to a slow internet connection? It doesn't seem to be a problem with aerial its' self. You could try and see if enabling the cache or downloading a video helps.

**Comment by john2691** [comment]
Could be a cache issue, as I selected "Always Download" and now it appears to work in the Preview mode. I'll keep an eye on it to see if it's fixed for good, thanks for your help.

**Comment by OrangeJedi** [comment]
Awesome. I'll take a look at the cache code and see if anything there might be the culprit. In the meantime I'll close the issue. Re-open it if you're still have the same problem.

**Comment by john2691** [comment]
In case anyone comes here with the same issue, the solution for me was to toggle all videos to "Always Download", and to turn off "Disable all Video Processing".
