### ISSUE TITLE
Add simple weather info

### ISSUE THREAD

**Issue by rezvee6** [OrangeJedi/Aerial#31]
I'd like to help with adding weather information. I was thinking a weather icon and temperature information would look sleek along with the time.

![david-kovalenko-414249-unsplashas](https://user-images.githubusercontent.com/26149161/82249760-4e5f9680-9942-11ea-9d53-cc443c865828.png)

**Comment by OrangeJedi** [comment]
Yeah. I would love help with this. Displaying the text is simple enough. Images wouldn't be much harder, you just need the files and the code to decide which one to display. You would also need the location of the user. Coordinate inputs would be easy to implement, but a city selector would be better for UX, just harder to implement. 
The hardest part is finding a good weather API to use. I haven't looked into this at all, but it would be the first step in getting weather into Aerial. Once you have the API you know what info you can display, and what info you need from the user.

**Comment by rezvee6** [comment]
I have found a pluggable & customisable weather widget that maybe you could use. The widget is customisable, includes icons.  Just need to figure a way to input city. Check it out
https://weatherwidget.io/

Maybe the widget below could be overlay-ed onto the canvas, with a transparent background? 

![Annotation 2020-05-18 202338](https://user-images.githubusercontent.com/26149161/82251718-9fbd5500-9945-11ea-9d0b-dcc8314c5980.png)

**Comment by OrangeJedi** [comment]
This looks great... except it doesn't seem like you can have the user change the location...
![image](https://user-images.githubusercontent.com/25063853/82252231-e1310e80-990b-11ea-936c-1f55e14e387c.png)

**Comment by rezvee6** [comment]
Hmm ok.. need to look into ways of getting by that maybe.
In the mean time I was able to get it working fine on my end as a rough prototype.

![Annotation 2020-05-18 204029](https://user-images.githubusercontent.com/26149161/82252942-e8760d80-9947-11ea-8187-f1beb871fd56.png)

**Comment by OrangeJedi** [comment]
Same here. I created a new "HTML" position type that lets you insert HTML into a position. It doesn't really solve the problem, but anyone could easily add the widget. Plus it opens the door for a bunch of other cool things.
![image](https://user-images.githubusercontent.com/25063853/82253478-4d147680-990e-11ea-848e-d9d6d89f031c.png)
![image](https://user-images.githubusercontent.com/25063853/82253515-5d2c5600-990e-11ea-9973-bd68fb5d71e8.png)

**Comment by rezvee6** [comment]
That's cool, could you share that build/new code?

**Comment by OrangeJedi** [comment]
I pushed it to the v0.6.0 branch (v0.6.0 is going to focus a lot on the text tab). [Here](https://github.com/OrangeJedi/Aerial/commit/ebc09d0d7428bbe88df1d862bcd291c4ec552fe3) is the commit. 

I also cleaned up the look of the textarea.

**Comment by x86txt** [comment]
> Hmm ok.. need to look into ways of getting by that maybe. In the mean time I was able to get it working fine on my end as a rough prototype.
> 
> ![Annotation 2020-05-18 204029](https://user-images.githubusercontent.com/26149161/82252942-e8760d80-9947-11ea-8187-f1beb871fd56.png)

Hi, can you share your code? I can't get it to stay boxed into that small area, it wants to take up half of my screen. Thanks!

**Comment by x86txt** [comment]
> Hmm ok.. need to look into ways of getting by that maybe. In the mean time I was able to get it working fine on my end as a rough prototype.
> 

Hi, can you share your code? I can't get the box smaller than 33% which takes way more screen than the widget needs.

![image](https://user-images.githubusercontent.com/34278354/146711415-b87ccf28-29bd-430c-952b-fe46e5e4deeb.png)
