### ISSUE TITLE
Random Screen Video Playback

### ISSUE THREAD

**Issue by VasilisPat** [OrangeJedi/Aerial#32]
Random video playback on double monitor setup.

1. I let the screensaver run automatically, only the main monitor works and second monitor is black
2. I change the option to display same video on all screens(functions normally).
3. I turn off same video playback on all screens, only the second monitor works and main monitor is black

**Aerial Version**
Beta 0.5.3

**Comment by OrangeJedi** [comment]
I'm going to assume you haven't enabled the "Only play videos on the primary screen" option, but it might be good to double check.
Do you have any text enabled? If you do does it display on both screens?
When the screensaver starts automatically does it always display on one screen, or does it seem random?

This sounds like it might be a bandwidth issue. You might want to check to see if you have anything that might prevent you from streaming two videos at once.

**Comment by VasilisPat** [comment]
I am trying to set it up so I can have different video displayed on the screens.

**Comment by OrangeJedi** [comment]
Yes. It's super weird that that isn't working. Both screens should be running the same code...

Can you check the following for me so I can help debug the issue:
* Do you have any text enabled? If you do, does it display on both screens?
* When the screensaver starts automatically does it always display on one screen, or does it seem random?
* Do you have the video cache enabled. Downloading the videos may help solve the issue. (You can uncheck all but 2 or 3 videos and just download those)
* Clicking the right arrow key will cycle the video, if you press it does anything change?

**Comment by VasilisPat** [comment]
Can't test any of the scenarios you mentioned above as of the problem described in #33 when downloading the .zip file. Now running the .src version, can't find any of the problems and everything seems to be working fine. 

Did a bit of search on my computer seems like a throttle for the specific app when caching, all others apps download at a rate of ~4.0Mbps, but Aerial stuck around ~1.0Mbps and less. Can't figure out if it is a problem on my machine or downloading from apple server..

Any ideas?

**Comment by OrangeJedi** [comment]
It could very well be Apple's servers, or your connection to their servers. I seemed to be downloading in the 200+Mbps range though. Let me know if caching the videos helps, if it does it probably was a network thing, if not then I have no idea what it is. Both of the screens should be running the exact same code.

**Comment by VasilisPat** [comment]
Seems to be a network issue. I set it to cache all checked videos and download speed have gone up to over 70Mbps and playback is smoother now. Although, should it download faster when I download all checked videos vs caching them while playing? Maybe dual monitor setup playing different videos reducing bandwith for each video when downloading while playing? But problem solved so I think I can close this issue.

Thanks a lot for your help and waiting for version 0.6!!
