### ISSUE TITLE
Can't start screensaver or enter settings menu

### ISSUE THREAD

**Issue by VasilisPat** [OrangeJedi/Aerial#33]
Downloaded a fresh copy of the .src file and installed it. In the Windows Screensaver Settings when I click either the settings or the preview button nothing is displayed, although multiple instances of areal are created when I open the task manager.

Perfomed a restart and a complete deletion of all aerial related files, doesn't see to fix the issue.

**Aerial Version**
Beta 0.5.3

**Comment by OrangeJedi** [comment]
Does double clicking the .scr file and opening it show the configuration screen?
I'm not sure what is going on, but I'll try to help. Also, did you download the .zip file or the .scr one?

**Comment by VasilisPat** [comment]
Downloaded the .zip file. No double clicking doesn't work either. 
Tried both .zip and .src of Beta 0.5.2, they do work without a problem. I will now try the .src of 0.5.3 and reply back.
Also if that helps you Windows Version is 10.0.18363.836

**Comment by OrangeJedi** [comment]
It looks like it might be a problem with your anti-virus? Have see seen any popups of that nature?

Also, I'm running the same version of Windows so that shouldn't be a problem.

**Comment by VasilisPat** [comment]
Created an exception for the extracted folder of the .zip and also disable the anti-virus temporarily. This doesn't seem to be the problem as it still doesn't show up anything. Although, the .src still works fine in both scenarios.

**Comment by OrangeJedi** [comment]
That's pretty weird. Have you cleared the files in `C:\Users\%Username%\AppData\Roaming\aerial`?
It is also possible that your anti-virus (or something else) deleted some file in the unzipped directory. 
If all else fails it looks like you got v0.5.2 working, which is a pretty stable version and should work fine.

**Comment by VasilisPat** [comment]
I have now removed the 0.5.2 version, deleted application folder and downloaded .src of 0.5.3, works fine with no problems. I will also try to recreate this scenario on another computer later and get back to you with further info.

Thanks for the help!!
