### ISSUE TITLE
Preview Button Inside Settings Menu

### ISSUE THREAD

**Issue by VasilisPat** [OrangeJedi/Aerial#35]
Is it possible to add a preview button inside the settings menu. Closing and opening the settings menu before being able to preview the screensaver is pretty simple, although when needed to be done multiple times can be a little be disturbing.

**Comment by OrangeJedi** [comment]
This is actually a great idea. What do you link of putting the buttons on the top bar and having two, one for a smaller, windowed preview, and one for the full screen. I drew a mock-up below. 
This is simple enough to code, but might take some time as I will need to change how the app closes itself as to not quit the config menu too.

![image](https://user-images.githubusercontent.com/25063853/82734996-b2d07c00-9cdb-11ea-9ab0-7649368d89c0.png)

**Comment by VasilisPat** [comment]
The position you proposed for the buttons appears to be great. Just a touch up from a visual perspective, please add a label saying "Preview" next to them. Also just to be sure, the buttons would be visible to all submenus right?

**Comment by OrangeJedi** [comment]
Yeah, this was a quick drawing done in paint. Colors and text are certain to change. And yes, this would be visible anywhere in the app.

**Comment by VasilisPat** [comment]
Perfect then, waiting to see it in action whenever you have the time to code it!! Also apologies for opening so many issues, I was really interested in the cDima's project and was dissapointed to see that no improvents were made. Until I found your project and I want to help and improve as much as possible. Your work is just amazing!

**Comment by OrangeJedi** [comment]
Thanks! I was using cDima's project but figured I could build something better, I'm glad to see other are enjoying it. As for a timeline, this should be in v0.6.0, if all goes well it should be out in the next 2 weeks.

**Comment by RebekahHsieh** [comment]
This may be a stupid question - but is it possible to shortcut to the aerial.scr file without it going to settings (eg - so you can create a load screensaver shortcut on desktop or via hotkeys).

**Comment by OrangeJedi** [comment]
@RebekahHsieh Yes there is! I actually have a shortcut set up on my computer.  `aerial.scr /s` should do the trick. See [here](https://github.com/OrangeJedi/Aerial/blob/master/CONTRIBUTING.md) for more information.

**Comment by OrangeJedi** [comment]
Added in [v0.5.4](https://github.com/OrangeJedi/Aerial/releases/tag/v0.5.4-beta)
