### ISSUE TITLE
BOTCHED UNINSTALL - CANNOT RE-INSTALL SUCCESSFULLY

### ISSUE THREAD

**Issue by TheRealDjElite** [OrangeJedi/Aerial#39]
[aerial-v0.5.3.zip]

So I changed the default folder (cuz I downloaded the 4K vids and re-encoded them), did a bunch of other stuff (sorry! wasn't keeping track!), and then AERIAL freaked out and wouldn't work. I somehow damaged what it knew of the file directory.

So I thought deleting the SCR file would be good enough and all I would have to do is re-install it.

Well, I was wrong. I completely forgot about the separate "configuration" program.

So yeah, it won't work for me now no matter what I do.

I NEED IT BACK. I NEED AERIAL IN MY LIFE. lol

Thanks in advance for any technical insight and advice (no personal opinions). 🤙🏽

**Comment by VasilisPat** [comment]
Can you try deleting the `C:\Users\%Username%\AppData\Roaming\aerial` folder? Also move the 4K videos to a temporary folder, download aerial .zip and then tranfer the videos to the new cache folder.

**Comment by TheRealDjElite** [comment]
WOOHOO! We have lift off!

I'll be careful this time. 😳

**Comment by TheRealDjElite** [comment]
Is this normal?

![image](https://user-images.githubusercontent.com/31051018/83338684-77e1c180-a262-11ea-9787-cdab95c08ee6.png)

**Comment by OrangeJedi** [comment]
You shouldn't be getting errors like that, though that it was an error looks like. Thanks for sharing the screenshot, it should help debug it faster.

It looks like your config file got corrupted somehow. Aerial was trying to write to the config file after downloading a video and it failed somehow. Did you edit the file or change anything in the `C:\Users\%Username%\AppData\Roaming\aerial` directory after your re-install? It might also be a file permissions error so you may want to check that.
Also, what where you doing when you got the error? Did you change any settings that may have caused problems? Does that app still run and have you gotten the error more than once?

If you keep getting the error your best bet will probably be to delete the `C:\Users\%Username%\AppData\Roaming\aerial\config.json`. This will delete any settings you have changed so be warned.

**Comment by TheRealDjElite** [comment]
So the DOWNLOAD problem had to do with a previously scheduled Power Outage that happened after my botched uninstall attempt. When the network came back online it wasn't 100%. I literally just rebooted the system and now the downloads are pouring in.

Thanks for the assist!
