### ISSUE TITLE
ChangeLog File

### ISSUE THREAD

**Issue by VasilisPat** [OrangeJedi/Aerial#40]
Can a ChangeLog file be created so changes can be tracked? Also brainstorming for new improvements would be made easier since all the current info would be centralized and explained better. If it's not possible from the aspect of time to work on it, I can help on editing and keeping it up to date.

**Comment by OrangeJedi** [comment]
We have our [version history](https://github.com/OrangeJedi/Aerial/wiki/Version-History) and I have a [project](https://github.com/OrangeJedi/Aerial/projects/1) that I use to track progress, but I don't think that those are really what you are talking about. There is also the git commits, but those are very brief and often vague.
Your description was brief, but what do you think a changelog should look like and where should it be located? I would be happy to help with it, if we feel that we need one.

**Comment by VasilisPat** [comment]
I was thinking more like an end user changelog, containing only what has been added to the new release or has been fixed/changed from a previous version, in a changelog.md file. My personal routine when I find out about a new project is to check if there is a changelog/manual file so I can see its features, since reading all the commits and the issues/topics added into project a bit time consuming. 

This idea came to me when I was brainstorming about enhancement to propose, so they can be added to the screensaver app. I went to the macOS version and searching about its features came across a very well written changelog, containing almost any option the app includes. I imagine ours to be like the features we have in the readme.md, but also containing pictures of the app and its changes without having to flood the main page of the project with a lot of information.

It would also be nice to have a documentation folder, containing a user manual, the changelog and a FAQ file. Basically make the whole project more accessible and easier to understand to an end user that doesn't have an advanced knowledge about programming. Being able to solve any problems quickly by searching through a document or seeing the FAQ's will help a lot in making the project grow. Also as more peolple come, new ideas, new suggestions and fixes will come.

If all this get's approved I am more excited than ever to make it happen.

**Comment by OrangeJedi** [comment]
I see what your saying and I think we should do it. I think the [Version History](https://github.com/OrangeJedi/Aerial/wiki/Version-History) wiki page is a good place to start, but we can also use the wiki feature to add a longer list of features, guides, and additional documentation. If you want to help out that would be awesome! I'll totally put some work in too. I've been wanting to do something like this for awhile but haven't had the time.

**Comment by VasilisPat** [comment]
@OrangeJedi Is there any chance to send me the changes coming to beta v6.0 so I can start preparing a changelog page? Also any photos would help.

**Comment by OrangeJedi** [comment]
I haven't worked too much on it yet, you can check the [project](https://github.com/OrangeJedi/Aerial/projects/1) to see what I've done. Currently it just the HTML text type. I'm working on multi-line\types in a position. Once I have a few features I can start prepping photos and descriptions for the changelog.

**Comment by VasilisPat** [comment]
@OrangeJedi Can I contact you via email?

**Comment by OrangeJedi** [comment]
Yes. You can contact me at orangejedi256@gmail.com. (I'll probably remove this message as soon as we get in contact)
