### ISSUE TITLE
Checking for half downloaded videos

### ISSUE THREAD

**Issue by VasilisPat** [OrangeJedi/Aerial#42]
Taking into consideration the error which popped in #39 should the app check every time it starts whether a video is downloaded partially or is corrupted?

More specifically I mean that if, for example, the computer loses connectivity with the internet when downloading a video it should delete it and start over again, to exclude any chance the video is corrupted. This example could also apply in a sudden reboot or loss of power.

I haven't reviewed the script that checks for the downloaded videos in depth, so if this has been taken care already just close/delete this issue.

**Comment by OrangeJedi** [comment]
Currently the video does not show as downloaded until the download is complete, but Aerial can create half downloaded files in certain situations. I'll look into what can be done about this, it will probably involve a temporary downloads folder or checks on videos on startup.

**Comment by OrangeJedi** [comment]
Fixed in [v0.5.4](https://github.com/OrangeJedi/Aerial/releases/tag/v0.5.4-beta)
