### ISSUE TITLE
I'm not getting all the screensavers

### ISSUE THREAD

**Issue by HeLiOn--PrImE** [OrangeJedi/Aerial#43]
The app doesn't seem to download the latest videos from apple.
My cache remains with 34 items.

Since the settings ui looks like in the screenshot below, I don't know exactly what to do to get all the content.

![image](https://user-images.githubusercontent.com/10486881/83660028-fa54e300-a5cc-11ea-90d3-81e5934d373f.png)

Any advice would be greatly appreciated

**Comment by OrangeJedi** [comment]
It looks like you are using cDima's version of Aerial. You are going to want to download this repo's version from [here](https://github.com/OrangeJedi/Aerial/releases)

**Comment by HeLiOn--PrImE** [comment]
Thank you, man. I'm getting the new ones now. And props for the UI with so many options.
