### ISSUE TITLE
Add Video Thumbnail in Settings Menu

### ISSUE THREAD

**Issue by VasilisPat** [OrangeJedi/Aerial#48]
Recently I have been deselecting videos from the menu, so I can see more often the ones I like th most. During this process I have been going back and forth between the videos.json and the cache path to determine which video I don't want, getting its id to crosscheck it with its name and finally deselect it. 
I think a good idea is to display a thumbnail for each video when clicking on it through the menu. This will make the video selection even easier. Of course the Video menu page has to be redesigned in order for that to be achieved. An idea would be to have the Profiles section in a seperate submenu.
Also I can make the thumbnails for all of the videos available on the [video list site](https://aerial-screensavers.netlify.com/). I was thinking a name format of videoid_thumb.jpg. Then, when a video was clicked a function could get the id of the video clicked, concate the _thumb.jpg to it and search for the thumbnail in a specified directory. I look forward to help with that!

**Comment by OrangeJedi** [comment]
When you click on the video in the video menu it should play the video on the right hand side of the screen like this:
![image](https://user-images.githubusercontent.com/25063853/84931904-b4018880-b090-11ea-9ef8-b0fead0148a0.png)

**Comment by VasilisPat** [comment]
Oh..Seems I have been concentrated only on cliking the check button and missing the central point of this menu page. A quick question before closing this issue: these videos are downloaded as temp to windows and deleted after a reboot or cached and deleted after the settings menu is closed? Or maybe none of those two?

**Comment by OrangeJedi** [comment]
It is (roughly) the same code as the screensaver. It will play the video from the cache if it is downloaded, otherwise the HTML video element is pointed at Apple's hosted location.

**Comment by VasilisPat** [comment]
Ok thanks. The reason asking is to include the info in the manual!!
