### ISSUE TITLE
Changes don't apply instantly

### ISSUE THREAD

**Issue by VasilisPat** [OrangeJedi/Aerial#49]
**Describe the bug**
When selecting and deselecting a video, downloading or deleting it doesn't take place until the menu is closed and reopened or the screensaver auto starts. Both _Automatically download when checked_ and _Automatically remove unchecked videos_ options are enabled. Also all videos are set _download when checked_.

**To Reproduce**
1. Enable _Automatically download when checked_ and _Automatically remove unchecked videos_.
2. Set all videos to _download when checked_.
3. Deselect a video and observe the cache folder, it has not been deleted.
4. Close and reopen settings menu, video is now deleted.

This also applies when downlaoding a new video. Updating the cache size after deselecting a video also indicates that the video has not been deleted.

**Expected behavior**
Shouldn't the changes take effect instantly?

**Aerial Version**
Beta 0.5.3

**Comment by OrangeJedi** [comment]
Your assessment of the situation is correct. Currently Aerial doesn't responded to cache setting changes until after a restart. I can see how this is bad, especially when deleting videos from the cache. I'll fix this in v0.6.0, it shouldn't be too bad.

**Comment by OrangeJedi** [comment]
Fixed in [v0.5.4](https://github.com/OrangeJedi/Aerial/releases/tag/v0.5.4-beta)
