### ISSUE TITLE
Video is stuck at it's end during playback

### ISSUE THREAD

**Issue by VasilisPat** [OrangeJedi/Aerial#50]
**Describe the bug**
Specifically only the Los Angeles Int'l Airport gets stucks after it is played all the way through and it doesn't transition to the next video. This can go for hours if the screensaver is not stopped. Sometimes it seems to get to next video and sometimes it doesn't. 

I don't know if is the video causing the issue or any option in the settings menu. When I play it back from file explorer seems to work fine.

**Aerial Version**
Beta 0.5.3

**Comment by OrangeJedi** [comment]
So it only happens on the LAX video and it happens consistently...
Is the video cached? If so try deleting it and re-downloading it. Otherwise I'm not entirely sure what could be causing the problem. I'll take a look at it as see if I can find anything.

**Comment by VasilisPat** [comment]
It happened to other videos too... All of them are downloaded. I tried deleting and redownloading, doesn't seem to fix the issue. Also did a fresh install of Aerial, the issue remains. This doesn't happen all the time, but when it happens, what I have noticed is that it is usually the 2nd or 3rd video from start. If the screensaver plays them without a problem the issue doesn't seem to reappear.

**Comment by OrangeJedi** [comment]
@VasilisPat Is this issue still happening? Or was it fixed in a recent update?
