### ISSUE TITLE
bad performance / massive framedrops ONLY as screensaver (not in preview)

### ISSUE THREAD

**Issue by christian-korneck** [OrangeJedi/Aerial#52]
I'm using Aerial `0.5.3` on Windows 10 2004 x64 (older AMD Radeon GPU with latest driver). It's an older/slower system, but `Aerial` works fine in preview mode or when started manually (`aerial.src /s`). With fine I mean I see a relatively high framerate, no or little notable frame drops.

Oddly it's very different when Aerial gets started by Windows as screen saver. The framerate drops down to something below 10 frames per second (massive frame drops).

I've enabled `disable all video processing`, set my Windows power setting to maximum performance, etc but it didn't improve.

The workaround I'm currently using is to start `aerial.src /s` as Scheduled Task after some idle time. With this workaround I'm getting the same good performance as when started as `preview` / manually.  It works fine, but has some disadvantages (only works when my user is interactively logged in / would need to set it up for every user, no lock screen).

(For anyone ending up here for this workaround this is what works for me:

- extract aerial to `c:\opt\aerial`
- copy `aerial.src` to `aerial.exe`
- create a shortcut in the same dir for `aerial.exe /s` named `aerial` (= `aerial.lnk`)
- right click `aerial.lnk` -> properties -> select "start maximized"
- create a scheduled task with trigger `idle` (set idle time under `conditions` tab) and action
  - program: `c:\windows\system32\cmd.exe`
  - args: `/c start /b c:\opt\aerial\aerial.lnk`

)

Does anyone have any idea why I'm seeing such a big performance difference between screensaver and preview mode?

**Comment by christian-korneck** [comment]
this is what it looks like (filmed with a phone's camera from a screen):
https://youtu.be/kKe97DvxVKQ

**Comment by OrangeJedi** [comment]
This is a known issue, but I have no idea what is causing it. For some reason Aerial uses a lot more power and has much lower frame rates when ran as a screensaver. I am pretty sure this issue is not with the app as the same code is being run in both instances. We are working on trying to find what is causing it and hopefully a solution.
Thanks for posting your work around! Obviously it isn’t perfect, but hopefully it could be helpful to some people.

**Comment by SquaredCircle84** [comment]
> 
> 
> I'm using Aerial `0.5.3` on Windows 10 2004 x64 (older AMD Radeon GPU with latest driver). It's an older/slower system, but `Aerial` works fine in preview mode or when started manually (`aerial.src /s`). With fine I mean I see a relatively high framerate, no or little notable frame drops.
> 
> Oddly it's very different when Aerial gets started by Windows as screen saver. The framerate drops down to something below 10 frames per second (massive frame drops).
> 
> I've enabled `disable all video processing`, set my Windows power setting to maximum performance, etc but it didn't improve.
> 
> The workaround I'm currently using is to start `aerial.src /s` as Scheduled Task after some idle time. With this workaround I'm getting the same good performance as when started as `preview` / manually. It works fine, but has some disadvantages (only works when my user is interactively logged in / would need to set it up for every user, no lock screen).
> 
> (For anyone ending up here for this workaround this is what works for me:
> 
>     * extract aerial to `c:\opt\aerial`
> 
>     * copy `aerial.src` to `aerial.exe`
> 
>     * create a shortcut in the same dir for `aerial.exe /s` named `aerial` (= `aerial.lnk`)
> 
>     * right click `aerial.lnk` -> properties -> select "start maximized"
> 
>     * create a scheduled task with trigger `idle` (set idle time under `conditions` tab) and action
>       
>       * program: `c:\windows\system32\cmd.exe`
>       * args: `/c start /b c:\opt\aerial\aerial.lnk`
> 
> 
> )
> 
> Does anyone have any idea why I'm seeing such a big performance difference between screensaver and preview mode?

Thank you for the writeup about how to create the task.  I've followed your directions but, unfortunately, it's not working for me for some reason.  I ran Task Scheduler as an administrator (even though my account is an administrator) just in case.  I have my actual screensaver set to blank.  I'm just trying to think of any outside variables that may be causing my issue.  Is there any other setting you can think of that might be missing?

**Comment by christian-korneck** [comment]
> unfortunately, it's not working for me for some reason. Nothing comes up for me at all.

here's a quick screen recording how to set it up (very raw and unedited, hope it still helps)
https://youtu.be/CGdxjzaXISg

any questions, let me know

**Comment by SquaredCircle84** [comment]
Wow, I not only appreciate the time you took to do this, but also the promptness in which you did it!  Thank you so much!  I followed the video to a T, but I'm still getting nothing.  The only difference is that I have everything extracted to C:\opt (not just aerial.exe and aerial.exe.lnk), and I have the timer set to 1 minute instead of 10.  When a minute ends, it's as if I just have the screensaver option completely turned off.  No brief command prompt popup or anything like that.  It's just nothing.

**Comment by christian-korneck** [comment]
when you run `aerial.exe /s` in a `cmd` shell, does it work there?

**Comment by SquaredCircle84** [comment]
> 
> 
> when you run `aerial.exe /s` in a `cmd` shell, does it work there?

Yes.

I was just with my son in another room and came back to the computer to see Aerial working, much to my surprise.  As previously mentioned, I have the task set to one minute.  I moved the mouse to bring the desktop back and started a timer.  After four minutes, the task ran.

??

**Comment by christian-korneck** [comment]
@SquaredCircle84 you're right, I can reproduce it on my machine. When you set the idle time to 1 minute it still takes about 4 minutes before the scheduled task starts. (The scheduled task on my PC is set for 30 minutes, so I didn't notice the delay before). 

I'm not sure why that is - the way Windows determines the idle state for scheduled tasks might be different than for screen savers.

**Comment by SquaredCircle84** [comment]
@christian-korneck Odd, but at least it works.  Again, thanks so much for your time and help!

**Comment by christian-korneck** [comment]
@SquaredCircle84 glad to hear, you're welcome

**Comment by OrangeJedi** [comment]
I'm going to close this even though this is still an issue, but recommend any further discussion be moved to #36
