### ISSUE TITLE
Javascript Error - Type Error [ERR_INVALID_ARG_TYPE]: The 'path' argument must be one of type string, Buffer or URL....

### ISSUE THREAD

**Issue by AndyDaSilva52** [OrangeJedi/Aerial#56]
**Describe the bug**
When clicked "Update cache" get the exception after open "Move Location" and Cancel

**To Reproduce**
1. Click "Move Location" at Video Cache
2. Click "OK" for the dialog message about the complete exclusion of the current cache.
3. Click on 'Cancel' (Folder Selection)
4. Click on "Update cache"
5. See error

**Expected behavior**
When click Cancel at step 3, it's expected to maintain the configuration of the path

**Aerial Version**
What version of Aerial are you running? v0.5.3

**Screenshots**
https://www.loom.com/share/c5b2d986b3c44cdcb9227397e23f7373
![Image of Exception](https://user-images.githubusercontent.com/1809812/90005617-d87f7880-dc6d-11ea-8cea-ad6c98a310c4.png)

**Additional context**

**Comment by OrangeJedi** [comment]
Yep! This is definitely a bug. It looks like when changing the cache folder if you don't select a folder it Aerial doesn't reset back to the old folder... A fix should go into the the next release. For now you should be able to work around it by moving the cache location to a valid folder.

**Comment by AndyDaSilva52** [comment]
Yes, tks
