### ISSUE TITLE
In "videos.json" the '105' 7C643A39-C0B2-4BA0-8BC2-2EAA47CC580E line should read....

### ISSUE THREAD

**Issue by TheRealDjElite** [OrangeJedi/Aerial#57]
"Over central Europe heading toward Russia"

**Comment by OrangeJedi** [comment]
Noted. The line currently reads `"105": "Over centra lEurope heading toward Russia",` (line 620 in videos.json) and should be changed to `"105": "Over central Europe heading toward Russia",` This can be easily fixed in the next update.

**Comment by OrangeJedi** [comment]
Fixed in [v0.5.4](https://github.com/OrangeJedi/Aerial/releases/tag/v0.5.4-beta)
