### ISSUE TITLE
Virus on Windows security scan/smart screen not allowing .scr to be installed

### ISSUE THREAD

**Issue by dougdalton** [OrangeJedi/Aerial#6]
When downloading in windows 10 with chrome, the scr wont even download as it is stopped as a virus

**To Reproduce**
1. download

**Expected behavior**
download finishes

**Screenshots**
https://pastepic.xyz/image/annotation-2020-03-29-234633.fvZsp

**Aerial Version**
0.4.0

**Additional context**
zip would only display config screen would not run

**Comment by OrangeJedi** [comment]
I would recommend doing one of the following:

1. Use a different browser. Firefox and Edge should both work.
2. Use the .zip file
3. Update Google Chrome. I saw a similar error when using chrome to download the .scr file, but was able to click a button to get around it. (Picture below)
![image](https://user-images.githubusercontent.com/25063853/77921858-86f5c480-725d-11ea-99ad-e4ce3c79402f.png)

It looks like you already tried the .zip though and had some issues. The .scr and .zip installations should behave very similarly however.  When you used the .zip did you right click on aerial.scr and click install? Aerial is a screensaver and will only run when installed as one.

**Comment by freddy1407** [comment]
used Firefox. Windows 10 itself is detecting a Virus, too. File was deleted.

Zip installation does not work. No Videos playing.
 ask me for more informations if you need!
really appreciate your work - Thank you!

**Comment by OrangeJedi** [comment]
In [v0.5.0](https://github.com/OrangeJedi/Aerial/releases/tag/v0.5.0-beta) I've put the .scr file in a .zip folder fixing this issue.
