### ISSUE TITLE
I am having issues installing the application

### ISSUE THREAD

**Issue by HeLiOn--PrImE** [OrangeJedi/Aerial#63]
I've been running an older version, of this screensaver, and I was notified that one of the issues I submitted was fixed.
However, I seem to be having issues installing the new version (Beta 0.5.4)

Bug description:
When I click preview or settings, the application does not start.
I cannot preview the screensaver or access the settings.

1. Download the application
2. Right click on the app and select install
3. When arriving to the screensaver options click settings or preview
4. Notice that nothing happens.

**Expected behavior**
When I click on settings, I expect the configuration panel to be displayed.

**Screenshots**
Several active processes can be noticed in the resource monitors after the actions above are performed
![image](https://user-images.githubusercontent.com/10486881/93928452-04892180-fd23-11ea-9a12-cc9b290c18de.png)

**Aerial Version**
Beta 0.5.4

**Additional context**
Up until this moment version 0.5.3 worked just fine. After removing it in order to install 0.5.4, it stopped working as well.

**Comment by VasilisPat** [comment]
Same thing happening over here. Doing a clean install allows the screensaver or the settings menu to launch only once. After the first time, a lot of process instances of aerial are created in the background while nothing is showing up. In my case reverting back to Beta 0.5.3 seems to work fine.

**Comment by JunyuT** [comment]
Can confirm. 0.5.4 only worked once for me, and subsequent launches will show up in task manager but nothing pops up. Installing 0.5.3 works however.

**Comment by joergbattermann** [comment]
Yep.. same for me.

**Comment by dexfitz** [comment]
I had a similar issue, where the application appeared to be running in the task manager but I could not select 'Settings' or 'Preview', and the video was not playing when the screen saver was triggered. 
Turns out that by changing the default cache location, a 'temp' folder was not being created, which was causing an unhandled warning (Issue #74). 

Perhaps try running the application in the [command line](https://github.com/OrangeJedi/Aerial/wiki/FAQ#how-can-i-start-aerial-in-screensaver-mode-without-waiting-for-it-to-turn-on) to see if you have a similar error (or an error as easily to diagnose as mine).

**Comment by VasilisPat** [comment]
Found a solution that works for me

- Uncheck "Immediately update video cache" option under Settings, Video Cache menu. (Also solution for Issue #74 )
- Create a subfolder inside the folder you have selected as cache location and name it temp. (Also solution for Issue #74 )

This should finaly give a solution for the users that aerial is not starting after installing Beta 0.5.4 version.

**Please provide feedback so I can publish a workaround to the main page of the project**

(Note: @HeLiOn--PrImE if you find this solution to work please mark the issue as closed, as to reduce the active issues)

**Comment by HeLiOn--PrImE** [comment]
@VasilisPat The thing is, I don't know where that folder is supposed to be. 
I'm trying to follow these install instructions.

```
.zip (recommended)
Download aerial-v0.5.4.zip
Extract the .zip file and navigate into the aerial-v0.5.3 folder
Right click on aerial.scr and click install
Configure your screen saver settings in the pop up window

.scr
Download aerial-0.5.4-scr.zip
Extract the .zip file
Right click on aerial.scr and click install
Configure your screen saver settings in the pop up window
```

What you're saying does make sense, but again... I don't know where the default location is supposed to be.
And because that folder is missing, I can't even reach the control panel.

**Comment by VasilisPat** [comment]
Default Aerial config location should be `C:\Users\%Username%\AppData\Roaming\aerial`
If so, the default video cache location is `C:\Users\%Username%\AppData\Roaming\aerial\cache`

Try starting with a fresh install of aerial and immediately make the corrections at my earlier comment.

To start fresh:
- Delete the aerial-v0.5.4 folder (the folder which contains the app)
- Delete `C:\Users\%Username%\AppData\Roaming\aerial`
- Perform a restart of your system

**Comment by HeLiOn--PrImE** [comment]
> Default Aerial config location should be `C:\Users\%Username%\AppData\Roaming\aerial`
> If so, the default video cache location is `C:\Users\%Username%\AppData\Roaming\aerial\cache`
> 
> Try starting with a fresh install of aerial and immediately make the corrections at my earlier comment.
> 
> To start fresh:
> 
> * Delete the aerial-v0.5.4 folder (the folder which contains the app)
> * Delete `C:\Users\%Username%\AppData\Roaming\aerial`
> * Perform a restart of your system

That seems to have done it. Aerial seems to be working again just fine now.
Note to self: change all existing settings and provide the app with a temp folder.

I should add this one last thing. After I did all the changes and clicked on preview, I received the following error:

![image](https://user-images.githubusercontent.com/10486881/107880629-ba2e5a00-6ee8-11eb-87b5-4e9167cb2c2b.png)

Clicking on preview again, started the screensaver properly with the settings I made.
Thank you for your assistance.
