### ISSUE TITLE
Convert Aerial to a self-launching, system tray application

### ISSUE THREAD

**Issue by richardmalone** [OrangeJedi/Aerial#65]
A solution to several problems:

a.) Aerial is a great screensaver that should future proof itself. Windows screensavers as we know them are eventually going to be deprecated as it is one of the most archaic parts of the system. The dialogue haven't changed much since 1995!
b.) The performance hit from running the screensaver as a screensaver (bug #36 )
c.) The task scheduler workaround also has its own issues--Windows idle conditions are not entirely coherent and it is easy these days to have a computer idling at >10% CPU due to background activity.

I believe the solution to all these problems is to emulate the system tray, launch and standby features of [Before Dawn screensaver](https://github.com/muffinista/before-dawn).

Other possibilities:
- Embed Aerial as a module in Before Dawn, although that would probably be quite difficult.
- A simple AutoIt script that deals with the screensaver launching and screen off functions. Something I will do myself, but thought I would see first what you thought of the above.

Regardless, thank you for a great piece of software!

**Comment by richardmalone** [comment]
I have discovered a tool that does basically what I want. 

[IdleRun](https://www.dcmembers.com/skrommel/download/idlerun/) is a tool that runs a program when the CPU is idle. 

I found that this is better than Windows scheduler, which tends to come out of Idle when launching Aerial and I have not found a way of it to ignore the spike in load when launching. 

Of course it is not that simple. The tool wants to run the same program every time that it reaches idle conditions, so I made a little batch script to check to see whether Aerial is running.

```@echo off
SETLOCAL EnableExtensions
set EXE=aerial.exe
FOR /F %%x IN ('tasklist /NH /FI "IMAGENAME eq %EXE%"') DO IF %%x == %EXE% goto FOUND
echo Not running
start D:\Libraries\Screensavers\aerial-v0.5.4\aerial.exe /s
goto FIN
:FOUND
echo Running
:FIN
exit
```
  
Then in IdleRun.ini have:

```[Action]
program=RunNHide.exe aerial.cmd
message=
exit=0
[Settings]
cputhreshold=5
checkinterval=1
idleduration=300
```
RunNHide stops the console window from showing on top of the screen.

Quite laborious, but seems to be the best solution at the moment. Eventually I will get around to making a new version of IdleRun to make it all a bit easier.

**Comment by Krakyn** [comment]
Just wanted to comment and encourage that this would be a great direction. The Windows screensaver feature is archaic and I wouldn't be surprised if it stops being supported in future versions of Windows. 

Another benefit of having a stand-alone program is that you would probably be able to use the official Apple 4k files in their native format (.mov) rather than having to download them and convert them to mp4.

**Comment by OrangeJedi** [comment]
Done! Thanks for the inspiration @richardmalone! Looking at Before Dawn gave me hope it could be done. Now Aerial is a self launching tray application that cn do a little bit more.

Unfortunately it doesn't put us in a much better position for 4k videos, but there's a few other things that could pan out.
