### ISSUE TITLE
Multimonitor support broken after 20H2 update

### ISSUE THREAD

**Issue by richardmalone** [OrangeJedi/Aerial#68]
Since 20H2 update, multimonitor support doesn't work as expected

Steps to reproduce the behaviour: Run screensaver with exact settings that worked on 20H1.  What happens is that the video that should be on the secondary screen is overlaid the primary monitor. 

Same behaviour if 'Only play videos on the primary screen' is selected, difference being that it is a black box.

**Screenshots**
![image](https://user-images.githubusercontent.com/6492842/97777517-b0b2f900-1b68-11eb-8f12-acdeb6d98617.png)

Aerial Version is 0.5.4

In case my monitor set up is causing the issue, my main monitor is 3440x1440 and secondary is mounted portrait on the left side with a resolution of 1080x1920

![image](https://user-images.githubusercontent.com/6492842/97777625-6d0cbf00-1b69-11eb-83e8-f0d2dbc30be7.png)

As I say, everything was working as expected until the most recent windows service pack update. 

Thanks, Richard

**Comment by tiago-bits** [comment]
Hi,

I just love this aerial screensaver :) it doens't start when connected to external monitor now.

It is also deleted from the screensaver menu randomly or when another screensaver is choosen - mine is in a folder inside user folders - I make riht click and install from there.

I have tried http://www.brianapps.net/saverstarter/ that starts up any other screensaver that I have installed but with aerial it goes to lock screen...


That would be so great to have the screensaver working again :)

**Comment by tiago-bits** [comment]
![imagem_2020-10-31_223843](https://user-images.githubusercontent.com/73757744/97791409-d6241f00-1bc9-11eb-9795-bed5579322b7.png)


I read on the internet that I should go to settings - and then choose troubleshoot power settings

Doing so ends the process saying that "screensaver is activated .....solved"

And by solved windows means deleted from the list

**Comment by OrangeJedi** [comment]
@richardmalone and @tiago-bits try updating to v1.0.0 and see if it changes things. The backend framework has been updated and it might have fixed the issue.

**Comment by OrangeJedi** [comment]
I can confirm that multi-monitor support is working fine on windows build 21H2. If you are still having issues after updating, please re-open the issue.
