### ISSUE TITLE
Changing default Video Cache location causes UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by dexfitz** [OrangeJedi/Aerial#74]
**Describe the bug**
Changing the default location of the application causes the application to bug out and not run correctly. 

**To Reproduce**
1. Download, extract and install v0.5.4
2. Change the default cache location (Open Settings... > Video Cache > Move Location)
3. Close the settings page. 
4. Screen saver does not run (black screen when triggered). Cannot select Settings or Preview. 
5. Application is still running (can be seen in Windows Task Manager).

**Expected behavior**
The application should not crash when default settings are changed. 

**Screenshots**
Instead of screenshots, I am opting for debugging output, which I gathered by testing the application by using the command line ([documented here](https://github.com/OrangeJedi/Aerial/wiki/FAQ#how-can-i-start-aerial-in-screensaver-mode-without-waiting-for-it-to-turn-on)):
```shell
C:\Download-Path\aerial-v0.5.4>aerial.scr /s
```
which gave the following error: 

```shell
C:\Download-Path\aerial-v0.5.4>aerial.scr /s

C:\Download-Path\aerial-v0.5.4>
(node:6284) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir 'C:\NEW-LOCATION\cache\temp'
    at Object.readdirSync (fs.js:854:3)
    at Object.fs.readdirSync (electron/js2c/asar.js:605:39)
    at Object.fs.readdirSync (electron/js2c/asar.js:605:39)
    at clearCacheTemp (C:\Download-Path\aerial-v0.5.4\resources\app\app.js:517:18)
    at startUp (C:\Download-Path\aerial-v0.5.4\resources\app\app.js:187:5)
(node:6284) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir 'C:\NEW-LOCATION\cache\temp'
    at Object.readdirSync (fs.js:854:3)
    at Object.fs.readdirSync (electron/js2c/asar.js:605:39)
    at Object.fs.readdirSync (electron/js2c/asar.js:605:39)
    at clearCacheTemp (C:\Download-Path\aerial-v0.5.4\resources\app\app.js:517:18)
    at startUp (C:\Download-Path\aerial-v0.5.4\resources\app\app.js:187:5)
(node:6284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6284) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6284) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Aerial Version**
aerial-v0.5.4

**Additional context**
In my case, I changed the default location of the cache folder, but the application did not create the `temp` folder under this cache folder. I manually created this `temp` folder and the application has been working as expected ever since.

**Comment by VasilisPat** [comment]
Found the solution. 
- Uncheck "Immediately update video cache" option under Settings, Video Cache menu. 

Please report your result, to confirm that it works.

**Comment by OrangeJedi** [comment]
This should be a quick fix, and it's embarrassing that an error like this got through. I'll include a patch with whatever the next release is.
