### ISSUE TITLE
Well, I think this project is dead folks

### ISSUE THREAD

**Issue by unbeatable-101** [OrangeJedi/Aerial#76]
😢😭

**Comment by MadNBG** [comment]
My opinion: its not dead, it's finish. 
I recomended Aerial to a friend, he installed the latest version it and it works.
I don't miss any features (though not running 4k nor multiple monitors).
I am happy and if there would be an option to donate a beer, I would.
Hope it will work on Win11

**Comment by unbeatable-101** [comment]
If it works for you on Win10 it'll probably work on 11

**Comment by OrangeJedi** [comment]
Yep :) it died. Sorry about that. But I'm back to working on it now. As @MadNBG pointed out it is pretty close to finished, it still works for people after 2 years of inactivity. But there is still plenty that cn be added and lots of small bugs to be fixed. I plan on supporting the project long term now and slowly adding new features.
