### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by WildWolfBang** [OrangeJedi/Aerial#77]
**Describe the bug**
Not work at Beta 0.5.4, but work when I return back to Beta 0.5.3
**To Reproduce**
1. Right-click on aerial.scr and click test it reports an error.
2. See error

**Expected behavior**
It does not work.
**Screenshots**
![image](https://user-images.githubusercontent.com/17874410/106898612-6032d500-672f-11eb-9c8e-b00dea1addc5.png)

**Aerial Version**
Beta 0.5.4
**Additional context**
No

**Comment by OrangeJedi** [comment]
I am going to close this for now, if the problem re-occurs on v1.0.0 please re-open with any additional details.
