### ISSUE TITLE
Add the option to hide the mouse cursor

### ISSUE THREAD

**Issue by HeLiOn--PrImE** [OrangeJedi/Aerial#78]
**Is your feature request related to a problem? Please describe.**
The mouse cursor remains displayed over the screensaver.

**Describe the solution you'd like**
It would be nice to have an option in the panel to hide it.

**Describe alternatives you've considered**
Initially I thought of requesting a hidden mouse by default, but then I figured some people may want it in case the application stops responding. That's why I'm suggesting this as an option.

**Comment by tompazourek** [comment]
btw. seems like a dupe of #79
