### ISSUE TITLE
Feature request: add download button to cache on every video

### ISSUE THREAD

**Issue by abeulink** [OrangeJedi/Aerial#88]
Hello developers, 

**Please add download button to cache on every video.**

I just noticed, our company network lagged when Aerial started.
Now I have to cancel downloads, now I want to download the videos one for one.
Then I make backup of videos, to prevent I have to dowload the videos again. Damn good idea!!!

So I need a button...

**Comment by OrangeJedi** [comment]
If you go to the cache settings in the main menu there is an option to auto-download all of the checked videos. Do you feel this method is too confusing? Is there a way you think we can make it better?

**Comment by OrangeJedi** [comment]
I double checked the app and you can set all the videos (or all the checked videos) to download. Here's a screenshot:
![image](https://user-images.githubusercontent.com/25063853/194211886-93275c6a-4098-4229-9dd4-c76c5da08cde.png)
