### ISSUE TITLE
Solution to screensaver crashing after changing cache folder

### ISSUE THREAD

**Issue by CommieColin** [OrangeJedi/Aerial#90]
Provided by @VasilisPat - posting it here for folks still experiencing the issue so they don't have to go through a bunch of bug reports 

Issue: after changing the cache location from within the screensaver settings, the settings panel no longer opens and the screensaver will crash, creating multiple instances of aerial.exe in task manager.

This is caused by the screensaver not automatically creating a "temp" folder in the new cache directory, which in turn causes the app to crash upon opening.

Solution: manually create a folder labeled "temp" in the root directory of your cache location.

For example, I have my cache directed at my 1TB drive - E:\Aerial\ 

The folder structure needs to read E:\Aerial\temp\ in order for the screensaver to properly download and cache videos (which come out to over 20GB, which is why I changed from my C: drive in the first place) 

Thank you @VasilisPat for the solution - this is a lovely looking screensaver and I'm glad I can continue to use it without having to take up 20GB on my SSD

**Comment by megaroeny** [comment]
No need to open a duplicate issue, just comment on other issues. And no this isn't the issue. See my comment here: https://github.com/OrangeJedi/Aerial/issues/89#issuecomment-968495147

**Comment by CommieColin** [comment]
This is not a duplicate so much as bumping a solution for a common issue to the top of the page for new users who might not know where to look. This project does not seem to be in active development, so I don't see the harm in helping some new people avoid digging through bug reports to find a simple solution. 

It sounds like you're experiencing a similar issue where the screensaver fails to open at all to adjust settings. I was experiencing the same thing until trying the solution outlined above. Try deleting the aerial folder from your roaming AppData folder and install again.

**Comment by balajeek** [comment]
Thank you for the info, I did move the cache location to a network drive and since then it crashed and i couldn't get it work, after seeing your post i was able to make it work back after creating the temp folder.

Question:  first of all to install it I downloaded the aerial.zip and extracted into my download folder, and right click on aerial.scr and install, it shows aerial in the screen saver settings, but the .scr file is not in the windows folder or anywhere else, does this mean i have to keep the aerial folder which is in my download director?

Thank you.

**Comment by CommieColin** [comment]
> Thank you for the info, I did move the cache location to a network drive and since then it crashed and i couldn't get it work, after seeing your post i was able to make it work back after creating the temp folder.
> 
> Question: first of all to install it I downloaded the aerial.zip and extracted into my download folder, and right click on aerial.scr and install, it shows aerial in the screen saver settings, but the .scr file is not in the windows folder or anywhere else, does this mean i have to keep the aerial folder which is in my download director?
> 
> Thank you.

Hello,

I'm glad that worked for you. You are correct; installing the .scr file does not move it to the Windows directory or anywhere else. I've copied the entire aerial folder to the root of my C: drive so that it doesn't get in the way. You can try doing the same without uninstalling the screensaver first, but if that causes issues then simply uninstall and place the screensaver folder in your desired directory before installing the .scr file

**Comment by OrangeJedi** [comment]
This issue is now fixed in v1.0.1!
