### ISSUE TITLE
New Icon for Aerial

### ISSUE THREAD

**Issue by OrangeJedi** [OrangeJedi/Aerial#99]
With Aerial now being a stand alone app it finally needed an icon/logo for it to have a nice visual presence. I threw together something quick and I'm not satisfied with how it turned out. I'd love for someone to make or suggest a better idea for a Aerial icon as I'm not the best at visual design. 

Here's the current design for reference; I have no attachment to it whatsoever.

![icon (128)](https://user-images.githubusercontent.com/25063853/194214246-9ef9c434-e0b1-434c-b563-3f8d93e002ff.png)

I am excited to see what the community can come up with!

**Comment by TheFreshPrins** [comment]
don't know if you like this one, my brother made it for you. [https://photos.app.goo.gl/wZJgKM1ugTxZ2AGYA](url)

**Comment by TheFreshPrins** [comment]
Update: My brother made a second icon which is a bit similar as for the mac variant.:
https://photos.app.goo.gl/KzTrPFhRGgRpAdF69

**Comment by OrangeJedi** [comment]
Thanks! Those both look awesome. I'll probably leave this issue open until around the next big release of Aerial and then we can have the community vote between the two (and any others anyone makes).

**Comment by OrangeJedi** [comment]
@TheFreshPrins It looks like the first icon won the vote! (see #129). Do you think you could send me that high-res version?

**Comment by TheFreshPrins** [comment]
> @TheFreshPrins It looks like the first icon won the vote! (see #129). Do you think you could send me that high-res version?

Hey Jedi, Looks like my brother lost the original file of the first icon which won. I forgot to vote in #129 and would have voted for option 3. I do have the high res version of that variant. If there would be a new version in the nearby future just let me know and I could send you that one. :)
